#!/bin/bash
source .values
COMMAND=$1
WORKSPACE=${TF_VAR_hostname:-default}

if [ -z "$TF_VAR_subscription_id" ] || [ -z "$TF_VAR_tenant_id" ] || [ -z "$TF_VAR_resource_group_name" ]; then
  echo "Error: One or more required variables are not set"
  exit 1
fi


function apply() {
  (cd $1; terraform workspace select -or-create $WORKSPACE && terraform init && terraform apply -auto-approve)
}

function destroy() {
  (cd $1; terraform workspace select -or-create $WORKSPACE && terraform destroy -auto-approve)
}

function up() {
    time(
    apply ../../infra/namespaces/
    apply ../../infra/network-policies/
    apply ../../infra/ingress/cert-manager
    apply ../../infra/ingress/$INGRESS_TYPE
    apply ../../infra/dashboard
    )
}

function down() {
    time(
    destroy ../../infra/dashboard
    destroy ../../infra/ingress/$INGRESS_TYPE
    destroy ../../infra/ingress/cert-manager
    destroy ../../infra/network-policies/
    destroy ../../infra/namespaces/
    )
}

if   [ "${COMMAND}" = "init" ]; then up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi