#!/bin/bash
source ../.values
export COMMAND=$1

function delete_secret_sub() {
    kubectl -n $1 delete secret --ignore-not-found docker-registry $2 $ 3
}

function create_secret_sub() {
  delete_secret_sub $1 $2 $3
  kubectl -n $1 create secret docker-registry $2 \
    --docker-server=$3 \
    --docker-username=$mailVar \
    --docker-password=$pwVar \
    --docker-email=$mailVar
}

function delete_secret() {
  delete_secret_sub $1 secret-name registry-name
}

function create_secret() {
  create_secret_sub $1 secret-name registry-name
}

function input_secret() {
  echo We now need the credentials to login to artifactory docker registry
  read -p "email: " mailVar
  printf "password: "
  while IFS= read -p "$prompt" -r -s -n 1 char; do
    if [[ $char == $'\0' ]]; then
      break
    fi
    prompt='*'
    pwVar+="$char"
  done
  echo "" # add echo to prevent -n errors
}

if [ "${COMMAND}" = "init" ]
then
    input_secret

    for val in ${namespaces[@]}; do
        create_secret $val
    done
elif [ "${COMMAND}" = "prune" ]
then
    for val in ${namespaces[@]}; do
        delete_secret $val
    done
else
    echo Doing nothing !
fi





