#!/bin/bash
COMMAND=$1
IMAGE_ARCH=$2 && [ -z "$IMAGE_ARCH" ] && IMAGE_ARCH=`kubectl version --output=json | grep "linux/arm64" > /dev/null && echo "-arm64v8"`

function up() {
    helm install --create-namespace\
    --set image.arch=$IMAGE_ARCH \
    --set ingress.hosts=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` \
    --namespace `pwd | rev | cut -d '/' -f3 | rev` \
    `cat ./Chart.yaml | grep "name" | cut -d':' -f2 | xargs` ./
}

function down() {
    helm uninstall \
    --namespace `pwd | rev | cut -d '/' -f3 | rev` \
    `cat ./Chart.yaml | grep "name" | cut -d':' -f2 | xargs`
}

function proxy() {
    kubectl port-forward deployment/`cat ./Chart.yaml | grep "name" | cut -d':' -f2 | xargs` \
    `cat ./values.yaml | grep "port" | cut -d':' -f2 | xargs`:`cat ./values.yaml | grep "port" | cut -d':' -f2 | xargs` \
    -n `pwd | rev | cut -d '/' -f3 | rev`
}

if   [ "${COMMAND}" = "init" ]; then up;
elif [ "${COMMAND}" = "prune" ]; then down;
elif [ "${COMMAND}" = "restart" ]; then down && up;
elif [ "${COMMAND}" = "lint" ]; then helm lint ./;
elif [ "${COMMAND}" = "proxy" ]; then proxy;

else echo Doing nothing !; fi