#!/bin/bash
COMMAND=$1
_Values_host_name=$2

function delete_secret() {
    kubectl delete secret --ignore-not-found trust-secret --namespace default
}

function create_secret() {
    delete_secret $1
    kubectl create secret generic trust-secret --from-file=./config --namespace default
    kubectl annotate secret trust-secret kubed.appscode.com/sync="" --namespace default
}

if [ "${COMMAND}" = "create" ]
then
    cp ../root/config/root.pem ./config
    create_secret

elif [ "${COMMAND}" = "delete" ]
then
    delete_secret
else
    echo Doing nothing !
fi