#!/bin/bash
COMMAND=$1
_Values_host_name=$2

function delete_secret() {
    kubectl delete secret --ignore-not-found trust-store-secret --namespace default
}

function create_secret() {
    delete_secret $1
    kubectl create secret generic trust-store-secret --from-file=./config --namespace default
    kubectl annotate secret trust-store-secret kubed.appscode.com/sync="" --namespace default
}

if [ "${COMMAND}" = "create" ]
then
    create_secret
elif [ "${COMMAND}" = "delete" ]
then
    delete_secret
else
    echo Doing nothing !
fi