#!/bin/bash
export COMMAND=$1

if [ "${COMMAND}" = "init" ]
then
    ./example-certs-manager create
    ./secret-manager create
elif [ "${COMMAND}" = "prune" ]
then
    ./secret-manager delete
else
    echo Doing nothing !
fi