#!/bin/bash
source .values

export COMMAND=$1

function up() {
    kubectl apply -f ./templates/pvc -n ${NAMESPACE}
    kubectl apply -f ./templates/ -n ${NAMESPACE}
#    minikube service grafana-ip-service --url -n ${NAMESPACE}
}

function down() {
    kubectl delete --ignore-not-found -f ./templates -n ${NAMESPACE}
}

if [ "${COMMAND}" = "up" ]
then
    up
elif [ "${COMMAND}" = "down" ]
then
    down
elif [ "${COMMAND}" = "prune" ]
then
    down
    kubectl delete --ignore-not-found -f ./templates/pvc -n ${NAMESPACE}
else
    echo Doing nothing !
fi
