#!/bin/bash
COMMAND=$1
SECRET_FILE=$2

[ -z "$SECRET_FILE" ] && echo variable not set && exit

function delete_secret() {
    kubectl delete secret --ignore-not-found authentication-secret --namespace default
}

function create_secret() {
    delete_secret $1
    kubectl create secret generic authentication-secret --from-file=${SECRET_FILE} --namespace default
    kubectl annotate secret authentication-secret kubed.appscode.com/sync="secret-sync=enabled" --namespace default
}

if [ "${COMMAND}" = "create" ]
then
    create_secret
elif [ "${COMMAND}" = "delete" ]
then
    delete_secret
else
    echo Doing nothing !
fi