#!/bin/bash
COMMAND=$1

function read_secret() {
    [ ! -f "./config/auth" ] && echo please enter password for user admin && htpasswd -c ./config/auth admin
}

if [ "${COMMAND}" = "init" ]
then
    read_secret
    ./secret-manager create ./config/auth
elif [ "${COMMAND}" = "prune" ]
then
    ./secret-manager delete ./config/auth
else
    echo Doing nothing !
fi