  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: bank-vault-example
    namespace: example
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: vault
    template:
      metadata:
        labels:
          app.kubernetes.io/name: vault
        annotations:
          vault.security.banzaicloud.io/vault-addr: "http://vault.vault:8200" # optional, the address of the Vault service, default values is https://vault:8200
          vault.security.banzaicloud.io/vault-role: "my-secret-role" # optional, the default value is the name of the ServiceAccount the Pod runs in, in case of Secrets and ConfigMaps it is "default"
          vault.security.banzaicloud.io/vault-skip-verify: "true" # optional, skip TLS verification of the Vault server certificate
          vault.security.banzaicloud.io/vault-agent: "false" # optional, if true, a Vault Agent will be started to do Vault authentication, by default not needed and vault-env will do Kubernetes Service Account based Vault authentication
      spec:
        serviceAccountName: my-secret-account
        containers:
          - name: alpine
            image: alpine
            command: ["sh", "-c", "echo $AWS_SECRET_ACCESS_KEY && echo going to sleep... && sleep 10000"]
            env:
              - name: username
                value: vault:secret/data/application/callee-service-application#username
              - name: password
                value: vault:secret/data/application/callee-service-application#password
