apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
 name: example-secret
 namespace: example
spec:
 kvVersion: 1
 backendType: vault
 vaultMountPoint: kubernetes
 vaultRole: k8s-role
 data:
 - name: RABBITMQ_USERNAME
   key: secret/application/callee-service-application
   property: username