grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s/grafana"
    serve_from_sub_path: false
  auth:
    disable_login_form: true
    disable_signout_menu: true
  auth.anonymous:
    enabled: true
    org_role: Admin
  security:
    allow_embedding: "true"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - access: proxy
      editable: true
      isDefault: false
      jsonData:
        timeInterval: 5s
      name: Loki
      orgId: 1
      type: loki
      url: http://loki:3100
      
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: my-cluster-issuer

    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1

  path: /grafana/?(.*)
  tls:
    - secretName: "root-certificate"