services:
  keycloak:
    container_name: ${_Values_root_name}-application
    image:  quay.io/keycloak/keycloak:24.0.1

    restart: 'no'
    ports:
      - "30200:8080"
    command: start --import-realm

    networks:
      - ${_Values_root_name}-net
    environment:
      #application
      - TZ=Europe/Berlin
      - JAVA_OPTS=-Xmx256m
      - KC_HTTP_RELATIVE_PATH=oidc
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME=localhost:30200

      #user
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

    volumes:
      - ./realm-config:/opt/keycloak/data/import

volumes:
    tmp:
    applogs:
    pgdata:

networks:
  keycloak-net:
    driver: bridge