apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}
stringData:
  POSTGRES_DB: sonar
data:
  POSTGRES_USER: c29uYXI=
  POSTGRES_PASSWORD: {{ .Values.database.password | default "sonar" | b64enc }}

  #echo -n sonarqube | base64
  #echo -n crNb2Z6mvBySRKwu | base64
  #echo -n Y3JOYjJaNm12QnlTUkt3dQ== | base64 -d