#!/bin/bash
COMMAND=$1
PROFILE=$2

HOST=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}'`
_Values_host_name=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` && [ -z "$_Values_host_name" ] && echo "Hostname is empty" && exit



function dynKubectl() {
for filename in $2/*.yaml; do
eval "cat <<EOF
$(<$filename)
EOF
" | kubectl $1 -f -
done
}

function up() {
    helm repo add kiali https://kiali.org/helm-charts > /dev/null
    helm install kiali-server kiali/kiali-server --namespace istio-system --create-namespace --version 1.47.0 -f ./values.yaml
    dynKubectl apply ./ingress
}

function down() {
    helm uninstall kiali-server --namespace=istio-system
    dynKubectl delete ./ingress
}


if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi

#Sample query: {namespace="example-tenant-5a2f",container="callee-service-application"}
