replicaCount: 1
maxReplicas: 3

ingress:
  paths: /core

image:
  repository: "goafabric/core-service-quarkus"
  pullPolicy: Always #IfNotPresent
  pullSecrets:

resourcesAnnotations:
  resources:
    requests:
      memory: 32M
      cpu: 250m

  args: ["-Xmx64M"]

readinessProbe:
  initialDelaySeconds: 5

service:
  type: ClusterIP
  port: 8080

postgresql:
  host: postgresql.data

kafka:
  enabled: false
  server: "kafka.data"
  port: "9092"

initContainers:
  - name: check-db-ready
    image: postgres:18.0
    command: ['sh', '-c','until pg_isready -h {{ .Values.postgresql.host }} -p 5432;do echo waiting for database; sleep 1; done;']

oidc:
  enabled:

multiTenancy:
  tenants: "0,5"

secrets:
  - name: postgresql-secret
  - name: kafka-secret
