apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  spring.datasource.username: cGVyc29uLXNlcnZpY2U=
  spring.datasource.password: {{ .Values.db.password | default "postgres" | b64enc }}

  quarkus.datasource.username: cGVyc29uLXNlcnZpY2U=
  quarkus.datasource.password: {{ .Values.db.password | default "postgres" | b64enc }}