#!/bin/bash
source .values

export COMMAND=$1

if [ "${COMMAND}" = "up" ]
then
    kubectl apply -f ./templates/ -n ${NAMESPACE}
#    minikube service prometheus-ip-service --url -n ${NAMESPACE}
elif [ "${COMMAND}" = "down" ]
then
    kubectl delete --ignore-not-found -f ./templates -n ${NAMESPACE}
else
    echo Doing nothing !
fi
