#!/bin/bash

function pack() {
    find $1 -not -path "." -type d -print0 | sort -hz | xargs -0 -I '{}' bash -c "echo '{}' && helm package '{}' -d ./spring"
}

pack ../../templates/example/spring/example
pack ../../templates/example/spring/example-tenant-0

#find ../../templates/example/spring/example -not -path "." -type d -print0 | sort -hz | xargs -0 -I '{}' bash -c "echo '{}' && helm package '{}' -d ./spring"
#find ../../templates/example/spring/example-tenant-0 -not -path "." -type d -print0 | sort -hz | xargs -0 -I '{}' bash -c "echo '{}' && helm package '{}' -d ./spring"


helm repo index ./spring --url https://goafabric.github.io/example-konstruction-kit/helm/charts/example/spring