#!/bin/bash

function pack1() {
    find "$1" -type f -name "Chart.yaml" -exec sh -c 'helm package "$(dirname "$0")" -d ./spring' {} \;
}

function pack2() {
    find "$1" -type f -name "Chart.yaml" -exec sh -c 'helm package "$(dirname "$0")" -d ./infra' {} \;
}

pack1 ../../templates/examle
pack1 ../../templates/core

pack2 ../../templates/infra

helm repo index ./spring --url https://goafabric.github.io/example-konstruction-kit/helm/charts/example/spring
helm repo index ./infra --url https://goafabric.github.io/example-konstruction-kit/helm/charts/example/infra