#!/bin/bash

if ! helm repo list | grep example-spring > /dev/null
then
    helm repo add example-spring https://goafabric.github.io/example-konstruction-kit/helm/charts/example/spring
    helm repo update 
fi

function helm_install() {
    helm install $1 example-spring/$1  \
    --create-namespace \
    --version $2 \
    --namespace=$NAMESPACE \
    --set ingress.hosts=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` \
    --set tenantId=$TENANT_ID 
#    --set image.arch="-native"`kubectl version --output=json | grep "linux/arm64" > /dev/null && echo "-arm64v8"`
}

function install() {
    NAMESPACE=example
    helm_install fhir-facade-application 1.0.6

    TENANT_ID=0
    NAMESPACE=example-tenant-$TENANT_ID
    helm_install callee-service-application 1.0.6

    helm_install person-service-application 1.0.6
    helm_install person-service-postgres 1.0.6
    helm_install person-service-batch 1.0.6

    TENANT_ID=5a2f
    NAMESPACE=example-tenant-$TENANT_ID
    helm_install callee-service-application 1.0.6

    helm_install person-service-application 1.0.6
    helm_install person-service-postgres 1.0.6
    helm_install person-service-batch 1.0.6

    NAMESPACE=default
    helm_install welcome-board 1.0.6
}

function uninstall() {
    NAMESPACE=example
    helm uninstall fhir-facade-application -n $NAMESPACE

    NAMESPACE=example-tenant-0
    helm uninstall callee-service-application -n $NAMESPACE
    helm uninstall person-service-application -n $NAMESPACE
    helm uninstall person-service-batch -n $NAMESPACE
    helm uninstall person-service-postgres -n $NAMESPACE

    NAMESPACE=example-tenant-5a2f
    helm uninstall callee-service-application -n $NAMESPACE
    helm uninstall person-service-application -n $NAMESPACE
    helm uninstall person-service-batch -n $NAMESPACE
    helm uninstall person-service-postgres -n $NAMESPACE

    NAMESPACE=default
    helm uninstall welcome-board

    kubectl delete pvc person-service-postgres-pvc -n example-tenant-0
    kubectl delete pvc person-service-postgres-pvc -n example-tenant-5a2f

    #kubectl delete ns example example-tenant-0
}

if   [ "$1" = "init" ] ; then install;
elif [ "$1" = "prune" ] ; then uninstall;
else echo "Doing nothing"; fi