apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 240
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "application.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
        {{- end }}

      {{ if .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}{{ .Values.image.arch }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: {{ include "application.fullname" . }}-config
            - configMapRef:
                name: {{ include "application.fullname" . }}-config-log
            - secretRef:
                name: {{ include "application.fullname" . }}-secret

          #resources and commands and args
          {{ if and (ne .Values.image.arch "-native") (ne .Values.image.arch "-native-arm64v8") }}
            {{- with .Values.resourcesAnnotations }}
            {{- toYaml . | nindent 10 }}
            {{- end }}
          {{- end }}

          {{ if or (eq .Values.image.arch "-native") (eq .Values.image.arch "-native-arm64v8") }}
            {{- with .Values.nativeAnnotations }}
            {{- toYaml . | nindent 10 }}
            {{- end }}
          {{- end }}

          volumeMounts:
            - mountPath: /usr/share/logs
              name: {{ include "application.fullname" . }}-applogs

      volumes:
        - name: {{ include "application.fullname" . }}-applogs
          emptyDir: {}
