replicaCount: 1

tenantId: 0
ingress:
  paths: /person
  enabled: true

image:
  repository: "goafabric/person-service"
  pullPolicy: Always #IfNotPresent
  pullSecrets:

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "true"

resourcesAnnotations:
  resources:
    requests:
      memory: 256M
      cpu: 250m

  command: ["java", "-Xms256M", "-Xmx256M", "-cp", "/app/resources:/app/classes:/app/libs/*",
            "org.goafabric.personservice.Application"]

nativeAnnotations:
  resources:
    requests:
      memory: 64M
      cpu: 250m

  args: ["-Xmx64M"]

readinessProbe:
  initialDelaySeconds: 5

service:
  type: ClusterIP
  port: 8080

initContainers:
  - name: check-db-ready
    image: postgres:16.2
    command: ['sh', '-c','until pg_isready -h person-service-postgres-postgresql-ha-pgpool -p 5432;do echo waiting for database; sleep 1; done;']

authentication:
  enabled:
