apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  POSTGRES_USER: Y29yZQ==
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc }}

  #echo -n core | base64
  #echo -n crNb2Z6mvBySRKwu | base64
  #echo -n Y3JOYjJaNm12QnlTUkt3dQ== | base64 -d