#!/bin/bash
COMMAND=$1
OPTS=$2

function up() {
    helm install \
    --set image.arch=`kubectl version | grep "Server Version" | grep "linux/arm64" > /dev/null && echo "-arm64v8"` \
    --set ingress.hosts=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` \
    --namespace `cat ./values.yaml | grep "namespace" | cut -d':' -f2 | xargs` \
    `cat ./Chart.yaml | grep "name" | cut -d':' -f2 | xargs` ./
}

function down() {
    helm uninstall \
    --namespace `cat ./values.yaml | grep "namespace" | cut -d':' -f2 | xargs` \
    `cat ./Chart.yaml | grep "name" | cut -d':' -f2 | xargs`
}

function package() {
  [ -z "$1" ] && echo "target directory not set" && exit
  helm package ./ -d ../../../../../../charts/$1/
  helm repo index ../../../../../../charts/$1/ --url https://github.com/goafabric/example-konstruction-kit/tree/refactoring/src/deploy/charts/quarkus
}

if   [ "${COMMAND}" = "up" ]; then up;
elif [ "${COMMAND}" = "down" ]; then down;
elif [ "${COMMAND}" = "restart" ]; then down && up;
elif [ "${COMMAND}" = "lint" ]; then helm lint ./;
elif [ "${COMMAND}" = "package" ]; then package $OPTS;

else echo Doing nothing !; fi