replicaCount: 1
maxReplicas: 3

tenantId: 0
ingress:
  paths: /person
  enabled: true

image:
  repository: "goafabric/person-service-quarkus"
  pullPolicy: IfNotPresent
  pullSecrets:

resourcesAnnotations:
  resources:
    requests:
      memory: 16M
      cpu: 250m

  args: ["-Xmx16M"]


readinessProbe:
  initialDelaySeconds: 1

service:
  type: ClusterIP
  port: 8080

initContainers:
  - name: check-db-ready
    image: postgres:17.2
    command: ['sh', '-c','until pg_isready -h person-service-postgres-postgresql-ha-pgpool -p 5432;do echo waiting for database; sleep 1; done;']

oidc:
  enabled:

multiTenancy:
  tenants: "0,5"
