replicaCount: 1
maxReplicas: 3

tenantId: 0
ingress:
  paths: /person

image:
  repository: "goafabric/person-service-quarkus"
  pullPolicy: Always #IfNotPresent
  pullSecrets:

resourcesAnnotations:
  resources:
    requests:
      memory: 16M
      cpu: 250m

  args: ["-Xmx32M"]


readinessProbe:
  initialDelaySeconds: 1

service:
  type: ClusterIP
  port: 8080

postgresql:
  host: postgresql.example

s3:
  endpoint: "http://s3-minio.data:9000"

kafka:
  enabled: true
  server: "kafka.data"
  port: "9092"

initContainers:
  - name: check-db-ready
    image: postgres:18.0
    command: ['sh', '-c','until pg_isready -h {{ .Values.postgresql.host }} -p 5432;do echo waiting for database; sleep 1; done;']

oidc:
  enabled:

multiTenancy:
  tenants: "0,5"

secrets:
  - name: postgresql-secret-example
  - name: kafka-secret
  - name: blob-storage-secret

global:
  management:
    port: