replicaCount: 1
maxReplicas: 3

tenantId: 0
ingress:
  paths: /callee
  enabled: true

image:
  repository: "goafabric/callee-service-quarkus"
  pullPolicy: IfNotPresent
  pullSecrets: 


resourcesAnnotations:
  resources:
    requests:
      memory: 16M
      cpu: 250m

  args: ["-Xmx32M"]

readinessProbe:
  initialDelaySeconds: 1

service:
  type: ClusterIP
  port: 8080

oidc:
  enabled:
