apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config-files
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  nginx.conf: >-
    events {
    }
    http {
        server {
            listen 8080 default_server;
            root /www/data;
            location / {
            }
        }
    }
