apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "application.fullname" . }}
spec:
  parentRefs:
    - name: apisix
      namespace: ingress-apisix
      sectionName: https
  hostnames:
    - {{ .Values.ingress.hosts }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.ingress.paths }}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: {{ include "application.fullname" . }}
          port: 80
