replicaCount: 1
maxReplicas: 3

ingress:
  paths: /invoice

image:
  repository: "goafabric/invoice-process-quarkus" # image name
  pullPolicy: Always #IfNotPresent
  pullSecrets:

resourcesAnnotations:
  resources:
    requests:
      memory: 64M
      cpu: 250m

  args: ["-Xmx64M"]

readinessProbe:
  initialDelaySeconds: 2

#initContainers:
#  - name: wait-for-redis
#    image: redis:7.2.4
#    command: ['sh', '-c', 'until redis-cli -h redis.invoice ping || redis-cli -h dragonfly.invoice ping; do echo waiting for redis; sleep 1; done;']

service:
  type: ClusterIP
  port: 8080

oidc:
  enabled:

secrets:
  - name: blob-storage-secret
  - name: redis-secret

