replicaCount: 1
maxReplicas: 3

ingress:
  paths: /core-frontend

image:
  repository: "goafabric/core-fe" # image name
  pullPolicy: IfNotPresent #Always
  pullSecrets: 

resourcesAnnotations:
  resources:
    requests:
      memory: 10M
      cpu: 250m

readinessProbe:
  initialDelaySeconds: 2
#  scheme: HTTPS

service:
  type: ClusterIP
  port: 80

oidc:
  enabled:



