replicaCount: 1

ingress:
  paths: /core-frontend

image:
  repository: "goafabric/core-fe" # image name
  pullPolicy: IfNotPresent #Always
  pullSecrets: 


  config.alpha.linkerd.io/proxy-enable-native-sidecar: "false" # https://linkerd.io/2.15/reference/proxy-configuration/, https://linkerd.io/2024/02/21/announcing-linkerd-2.15/, https://github.com/linkerd/linkerd2/releases

resourcesAnnotations:
  resources:
    requests:
      memory: 10M
      cpu: 250m

readinessProbe:
  initialDelaySeconds: 2
#  scheme: HTTPS

service:
  type: ClusterIP
  port: 80

oidc:
  enabled:



