replicaCount: 2

ingress:
  paths: /catalog
  enabled: true

image:
  repository: "goafabric/catalog-batch-service"
  pullPolicy: IfNotPresent
  pullSecrets:

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "true"

resourcesAnnotations:
  resources:
    requests:
      memory: 256M
      cpu: 250m

  command: ["java", "-Xms256M", "-Xmx256M", "-cp", "/app/resources:/app/classes:/app/libs/*",
            "org.goafabric.catalogservice.Application"]

nativeAnnotations:
  resources:
    requests:
      memory: 64M
      cpu: 250m

  args: ["-Xmx64M"]

readinessProbe:
  initialDelaySeconds: 2

service:
  type: ClusterIP
  port: 8080

initContainers:
  - name: check-db-ready
    image: postgres:16.2
    command: ['sh', '-c','until pg_isready -h core-postgres-postgresql-ha-pgpool -p 5432;do echo waiting for database; sleep 1; done;']

database:
  password:

authentication:
  enabled: