replicaCount: 1
maxReplicas: 3

ingress:
  paths: /catalog

image:
  repository: "goafabric/catalog-batch-service-quarkus"
  pullPolicy: Always #IfNotPresent
  pullSecrets:

resourcesAnnotations:
  resources:
    requests:
      memory: 32M
      cpu: 250m

  args: ["-Xmx64M"]

readinessProbe:
  initialDelaySeconds: 2

service:
  type: ClusterIP
  port: 8080

postgresql:
  host: postgresql.data

initContainers:
  - name: check-db-ready
    image: postgres:18.0
    command: ['sh', '-c','until pg_isready -h {{ .Values.postgresql.host }} -p 5432;do echo waiting for database; sleep 1; done;']

oidc:
  enabled:

secrets:
  - name: postgresql-secret
