#!/bin/bash
container machine rm micro

container machine create local/ubuntu --name micro --cpus 6 --memory 8g
sleep 1
container machine run -n micro sudo snap install microk8s --classic --channel=1.34/stable
container machine run -n micro sudo microk8s enable hostpath-storage

container machine run -n micro sudo microk8s config view > ~/.kube.profile/.kube.micro/config
container machine run -n micro sudo microk8s config view > ~/.kube/config

 kubectl patch svc apisix-gateway -n ingress-apisix --type='json' -p='[{"op":"replace","path":"/spec/ports/1/nodePort","value":32443}]'

#container machine run -n micro "sudo bash -c 'IP=\$(hostname -I | awk \"{print \\\$1}\") && sudo microk8s enable metallb:\$IP-\$IP'"

./stack init