#!/bin/bash
#container build -t docker.io/goafabric/microk8s:1.34 -f Dockerfile.microk8s . && container image push docker.io/goafabric/microk8s:1.34

container machine rm microk8s
container image pull goafabric/microk8s:1.34
container machine create goafabric/microk8s:1.34 --name microk8s --cpus 6 --memory 8g
sleep 1
echo starting microk8s
container machine run "sudo sh -c 'echo \"nameserver 8.8.8.8\" >> /etc/resolv.conf'"
container machine run -n microk8s "sudo snap ack /opt/microk8s/microk8s_*.assert && sudo snap install /opt/microk8s/microk8s_*.snap --classic"
container machine run -n microk8s sudo microk8s enable hostpath-storage

container machine run -n microk8s sudo microk8s config view > ~/.kube.profile/.kube.micro/config
container machine run -n microk8s sudo microk8s config view > ~/.kube/config

./stack init && ./machine-start
kubectl patch svc apisix-gateway -n ingress-apisix --type='json' -p='[{"op":"replace","path":"/spec/ports/1/nodePort","value":32443}]'
