#!/bin/bash
source ~/.kube/values

COMMAND=$1
WORKSPACE=$TF_VAR_hostname

function apply() {
  (cd $1; terraform workspace select -or-create $WORKSPACE && terraform apply -auto-approve)
}

function destroy() {
  (cd $1; terraform workspace select -or-create $WORKSPACE && terraform destroy -auto-approve)
}

function up() {
    time(
    apply ../../infra/ingress
    apply ../../infra/monitoring
    apply ../../infra/grafana
    apply ../../infra/oidc
    apply ../../example
    apply ../../core
    apply ../../infra/message-broker
    )
}

function down() {
    time(
    destroy ../../infra/message-broker
    destroy ../../core
    destroy ../../example
    destroy ../../infra/oidc
    destroy ../../infra/monitoring
    destroy ../../infra/grafana
    destroy ../../infra/ingress
    )
}

if   [ "${COMMAND}" = "init" ]; then up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi