#!/bin/bash
source .values
COMMAND=$1
WORKSPACE=$TF_VAR_hostname

function apply() {
  (cd $1; terraform workspace select -or-create $WORKSPACE && terraform init && terraform apply -auto-approve)
}

function destroy() {
  (cd $1; terraform workspace select -or-create $WORKSPACE && terraform destroy -auto-approve)
}


function up() {
    time(
    apply ../../infra/namespaces/
    apply ../../infra/network-policies/
    apply ../../infra/ingress/cert-manager
    apply ../../infra/ingress/apisix
    apply ../../infra/ingress/gateway
    apply ../../infra/dashboard
    )
}

function down() {
    time(
    destroy ../../infra/dashboard
    destroy ../../infra/ingress/gateway
    destroy ../../infra/ingress/apisix
    destroy ../../infra/ingress/cert-manager
    destroy ../../infra/network-policies/
    destroy ../../infra/namespaces/
    destroy ./
    )
}

if   [ "${COMMAND}" = "init" ]; then up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi