#!/bin/bash
source ~/.kube/values

COMMAND=$1
WORKSPACE=$TF_VAR_hostname

function apply() {
  (cd $1; terraform workspace select -or-create $WORKSPACE && terraform init && terraform apply -auto-approve)
}

function destroy() {
  (cd $1; terraform workspace select -or-create $WORKSPACE && terraform destroy -auto-approve)
}

function up() {
    time(
    apply ../../infra/ingress/apisix
    apply ../../infra/dashboard
    apply ../../infra/grafana
    apply ../../infra/oidc
#   apply ../../example
    apply ../../core
    apply ../../event
    )
}

function down() {
    time(
    destroy ../../event
    destroy ../../core
    destroy ../../example
    destroy ../../infra/oidc
    destroy ../../infra/dashboard
    destroy ../../infra/grafana
    destroy ../../infra/ingress
    destroy ../../infra/cert-manager
    destroy ../../infra/ingress/apisix
    )
}

if   [ "${COMMAND}" = "init" ]; then up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi