apiVersion: v1
entries:
  event-dispatcher-service-application:
  - apiVersion: v2
    appVersion: 3.1.2
    created: "2023-11-05T11:31:42.765427+01:00"
    description: event-dispatcher-service-application
    digest: 3c2f152417e66d5c59e0218a69ac3dcab4acb1047c3349e45a7289c939aebcf5
    name: event-dispatcher-service-application
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/infra/event-dispatcher-service-application-1.0.0.tgz
    version: 1.0.0
  jaeger-all:
  - apiVersion: v2
    appVersion: 1.46.0
    created: "2023-11-05T11:31:42.765536+01:00"
    description: jaeger-all
    digest: a259c7a342884a81bc2b7a747cb0f77e23eb9e6764f1d004bfd4ec1e40603936
    name: jaeger-all
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/infra/jaeger-all-1.46.0.tgz
    version: 1.46.0
  rabbitmq:
  - apiVersion: v2
    appVersion: 3.12.1-management
    created: "2023-11-05T11:31:42.765711+01:00"
    description: rabbitmq
    digest: a03eecb92771d666cd8e908bce3523ee3366b5664af630fa540e7786e54a7f95
    name: rabbitmq
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/infra/rabbitmq-3.12.1.tgz
    version: 3.12.1
  spring-auth-server-application:
  - apiVersion: v2
    appVersion: 1.0.3
    created: "2023-11-05T11:31:42.765908+01:00"
    description: spring-auth-server-application
    digest: 001f7c3a271d256717a3683f54b70c768b3193ab371017b530c78376843a86d9
    name: spring-auth-server-application
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/infra/spring-auth-server-application-1.1.1.tgz
    version: 1.1.1
  welcome-board:
  - apiVersion: v2
    appVersion: 1.20.2
    created: "2023-11-05T11:31:42.766094+01:00"
    description: welcome-board
    digest: 6cbbd6681ab7880ffbebbbbe4ae4a1777fe4af4553195b345f02919135c7c601
    name: welcome-board
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/infra/welcome-board-1.1.1.tgz
    version: 1.1.1
generated: "2023-11-05T11:31:42.765124+01:00"
