apiVersion: v1
entries:
  event-dispatcher-service-application:
  - apiVersion: v2
    appVersion: 3.1.2
    created: "2023-11-05T09:11:15.476314+01:00"
    description: event-dispatcher-service-application
    digest: 6000e03222da8133b85d31212ab07fa20f9bbe72b947461510574cf9ef80b630
    name: event-dispatcher-service-application
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/infra/event-dispatcher-service-application-1.0.0.tgz
    version: 1.0.0
  jaeger-all:
  - apiVersion: v2
    appVersion: 1.46.0
    created: "2023-11-05T09:11:15.476418+01:00"
    description: jaeger-all
    digest: 7ccc1f16eea45bfcd44c65bc8b7d595f91dd379b48a5f781b14ef1e6b273671c
    name: jaeger-all
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/infra/jaeger-all-1.46.0.tgz
    version: 1.46.0
  rabbitmq:
  - apiVersion: v2
    appVersion: 3.12.1-management
    created: "2023-11-05T09:11:15.476582+01:00"
    description: rabbitmq
    digest: 1db1192d73f5c55a0d86251b3d91d627c47e9932fb3246713b18dd71a5639dc0
    name: rabbitmq
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/infra/rabbitmq-3.12.1.tgz
    version: 3.12.1
  spring-auth-server-application:
  - apiVersion: v2
    appVersion: 1.0.3
    created: "2023-11-05T09:11:15.476768+01:00"
    description: spring-auth-server-application
    digest: 96969f8c145fc10579b1cbf72cf9f5ae8731f200f611d3f8a3eabf44abb92434
    name: spring-auth-server-application
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/infra/spring-auth-server-application-1.1.1.tgz
    version: 1.1.1
  welcome-board:
  - apiVersion: v2
    appVersion: 1.20.2
    created: "2023-11-05T09:11:15.476957+01:00"
    description: welcome-board
    digest: b409592aa9d0f0174c04a7bb1bfcb3d74c1ee338f158d27ccaa7f5dc442a4859
    name: welcome-board
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/infra/welcome-board-1.1.1.tgz
    version: 1.1.1
generated: "2023-11-05T09:11:15.476026+01:00"
