apiVersion: v1
entries:
  event-dispatcher-service-application:
  - apiVersion: v2
    appVersion: 3.1.2
    created: "2023-11-11T09:28:55.935424+01:00"
    description: event-dispatcher-service-application
    digest: 3c340b64cd675efe3c75bf65c73f311de735e74740093885fd672ca1071e70e3
    name: event-dispatcher-service-application
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/infra/event-dispatcher-service-application-1.0.0.tgz
    version: 1.0.0
  jaeger-all:
  - apiVersion: v2
    appVersion: 1.46.0
    created: "2023-11-11T09:28:55.935526+01:00"
    description: jaeger-all
    digest: c04cafd26a6ee762eb8d9bfcec985e4c82f57568396025196119f2bcdcbc981a
    name: jaeger-all
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/infra/jaeger-all-1.46.0.tgz
    version: 1.46.0
  rabbitmq:
  - apiVersion: v2
    appVersion: 3.12.1-management
    created: "2023-11-11T09:28:55.935683+01:00"
    description: rabbitmq
    digest: 684a3687846f084302234f77ae002272363ce91b661d29a34947ee1fdfb4817b
    name: rabbitmq
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/infra/rabbitmq-3.12.1.tgz
    version: 3.12.1
  spring-auth-server-application:
  - apiVersion: v2
    appVersion: 1.0.3
    created: "2023-11-11T09:28:55.935881+01:00"
    description: spring-auth-server-application
    digest: f1964e7bc1cd1a5da6232bc9b94c0d248b3389f37dc7510c193b048ebc42a26f
    name: spring-auth-server-application
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/infra/spring-auth-server-application-1.1.1.tgz
    version: 1.1.1
  welcome-board:
  - apiVersion: v2
    appVersion: 1.20.2
    created: "2023-11-11T09:28:55.936148+01:00"
    description: welcome-board
    digest: 738c0ee7331789cbe8d8b3bc6bd66165b871029c49c29c14a43f2ee7483cd582
    name: welcome-board
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/infra/welcome-board-1.1.1.tgz
    version: 1.1.1
generated: "2023-11-11T09:28:55.935151+01:00"
