#!/bin/bash
COMMAND=$1
PROFILE=$2

function up() {
    kubectl apply -f ./templates/
}

function down() {
    kubectl delete --ignore-not-found -f ./templates/
}


if   [ "${COMMAND}" = "up" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "down" ]; then down;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi