#!/bin/bash
COMMAND=$1
PROFILE=$2

kubectl version | grep "Server Version" | grep "linux/arm64" > /dev/null && _Values_server_arch="-arm64v8"
_Values_host_name=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` && [ -z "$_Values_host_name" ] && echo "Hostname is empty" && exit

function up() {
    helm install --set image.arch=${_Values_server_arch} callee-service-application ./
}

function down() {
    helm uninstall callee-service-application;
}

if   [ "${COMMAND}" = "up" ]; then up;
elif [ "${COMMAND}" = "down" ]; then down;
elif [ "${COMMAND}" = "prune" ]; then down;
elif [ "${COMMAND}" = "restart" ]; then down && up;

else echo Doing nothing !; fi