apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #application
  TZ: Europe/Berlin

  #div
  #KC_HTTP_RELATIVE_PATH: "oidc"
  KC_PROXY: "edge"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME: "https://{{ .Values.ingress.hosts}}/oidc"

  #database
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://keycloak-postgres/keycloak"

  KC_LOG_LEVEL: "INFO"