#!/bin/bash
[ -z "$_Values_server_name" ] && echo "Server Name is empty" && exit
sed -i '' 's/SERVER_NAME/'"${_Values_server_name}"'/g' ./config/san.cnf

#variables
export DAYS_VALID="365"
export ROOT_FILE="../root/config/root"
export SERVER_FILE="./config/server"

# create key, won't ask for password because no encryption applied
openssl genrsa\
        -out ${SERVER_FILE}.key\
        4096

# create signing request (csr)
openssl req -new -sha512\
        -key ${SERVER_FILE}.key\
        -out ${SERVER_FILE}.csr\
        -config config/san.cnf\
        -extensions SAN

# create end entity certificate
openssl x509 -req -sha512 -days ${DAYS_VALID}\
        -in ${SERVER_FILE}.csr\
        -CA ${ROOT_FILE}.pem\
        -CAkey ${ROOT_FILE}.key\
        -CAcreateserial -out ${SERVER_FILE}.pem\
        -extfile config/san.cnf\
        -extensions SAN


# remove csr
rm ${SERVER_FILE}.csr
cp ./config/san.org ./config/san.cnf