#!/bin/bash
source ../../.values
export COMMAND=$1

function delete_secret() {
    kubectl delete secret --ignore-not-found server-certificate-secret -n $1
}

function create_secret() {
    delete_secret $1
    kubectl create secret tls server-certificate-secret --cert=./config/goafabric-server.pem --key=./config/goafabric-server.key -n $1
}

if [ "${COMMAND}" = "init" ]
then
    if kubectl get --ignore-not-found namespace linkerd | grep -q Active; then create_secret linkerd; fi
    create_secret kube-system

    for val in ${namespaces[@]}; do
      create_secret $val
    done
elif [ "${COMMAND}" = "prune" ]
then
    if kubectl get --ignore-not-found namespace linkerd | grep -q Active; then delete_secret linkerd; fi
    delete_secret kube-system

    for val in ${namespaces[@]}; do
      delete_secret $val
    done
else
    echo Doing nothing !
fi

