apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: deny-host-to-pod
spec:
  preDNAT: true
  applyOnForward: true
  selector: all()
  types:
    - Ingress
  ingress:
    - action: Deny
      source:
        nets:
          - "0.0.0.0/0"
      destination:
        selector: all()