apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "application.fullname" . }}-kong
  annotations:
    konghq.com/strip-path: 'true'
    cert-manager.io/cluster-issuer: my-cluster-issuer

spec:
  ingressClassName: kong
  tls:
    - hosts:
        - {{ .Values.ingress.hosts}}
      secretName: root-certificate
  rules:
    - host: {{ .Values.ingress.hosts}}
      http:
        paths:
          - path: {{ .Values.ingress.paths }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "application.fullname" . }}
                port:
                  name: http