replicaCount: 1

ingress:
  paths: /s3
  enabled: true
  authentication: none

image:
  repository: "quay.io/minio/minio"
  pullPolicy: IfNotPresent
  pullSecrets:

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "false"

resources:
  requests:
    memory: 128M
    cpu: 500m
#  limits:
#    cpu: 500m

readinessProbe:
  initialDelaySeconds: 2

service:
  type: ClusterIP

postgres:
  maxConnections: 30

persistence:
  storageClassName:

s3:
  password: