replicaCount: 1


image:
  repository: "goafabric/catalog-batch-service"
  pullPolicy: IfNotPresent #Always
  pullSecrets:

podAnnotations:
  linkerd.io/inject: disabled
  sidecar.istio.io/inject: "false"

resourcesAnnotations:
  resources:
    requests:
      memory: 256M
      cpu: 250m

  command: ["java", "-Xms256M", "-Xmx256M", "-cp", "/app/resources:/app/classes:/app/libs/*",
            "org.goafabric.catalogservice.Application"]

nativeAnnotations:
  resources:
    requests:
      memory: 64M
      cpu: 250m

  args: ["-Xmx64M"]

readinessProbe:
  initialDelaySeconds: 2

service:
  type: ClusterIP
  port: 8080

postgresql:
  host: postgresql.data

initContainers:
  - name: check-db-ready
    image: postgres:17.2
    command: ['sh', '-c','until pg_isready -h {{ .Values.postgresql.host }} -p 5432;do echo waiting for database; sleep 1; done;']
