apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9092
      targetPort: http
      protocol: TCP
      name: http
    - port: 9093
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    {{- include "application.selectorLabels" . | nindent 4 }}
