#!/bin/bash
COMMAND=$1

function up() {
    kubectl create ns mock 
    helm install \
    --set image.arch=`kubectl version --output=json | grep "linux/arm64" > /dev/null && echo "-arm64v8"` \
    --set ingress.hosts=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` \
    --namespace mock \
    `cat ./Chart.yaml | grep "name" | cut -d':' -f2 | xargs` ./
}

function down() {
    helm uninstall \
    --namespace mock \
    `cat ./Chart.yaml | grep "name" | cut -d':' -f2 | xargs`
}

function proxy() {
    kubectl port-forward deployment/`cat ./Chart.yaml | grep "name" | cut -d':' -f2 | xargs` \
    `cat ./values.yaml | grep "port" | cut -d':' -f2 | xargs`:`cat ./values.yaml | grep "port" | cut -d':' -f2 | xargs` \
    --namespace mock
}

if   [ "${COMMAND}" = "init" ]; then up;
elif [ "${COMMAND}" = "prune" ]; then down;
elif [ "${COMMAND}" = "restart" ]; then down && up;
elif [ "${COMMAND}" = "lint" ]; then helm lint ./;
elif [ "${COMMAND}" = "proxy" ]; then proxy;

else echo Doing nothing !; fi