#!/bin/bash
source ../../.values
COMMAND=$1
_Values_host_name=$2

function delete_secret() {
    kubectl delete secret --ignore-not-found server-certificate-secret -n $1
}

function create_secret() {
    delete_secret $1 && kubectl create secret tls server-certificate-secret --cert=./config/server.pem --key=./config/server.key -n $1
}

if [ "${COMMAND}" = "create" ]
then
    ./generate-server ${_Values_host_name}
    for val in ${namespaces[@]}; do
        if kubectl get --ignore-not-found namespace $val | grep -q Active; then echo namespace: $val && create_secret $val; fi
    done
elif [ "${COMMAND}" = "delete" ]
then
    for val in ${namespaces[@]}; do
        if kubectl get --ignore-not-found namespace $val | grep -q Active; then echo namespace: $val && delete_secret $val; fi
    done
else
    echo Doing nothing !
fi