#!/bin/bash
COMMAND=$1
PROFILE=$2

#https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-eck.html

function up() {
    kubectl apply -f https://download.elastic.co/downloads/eck/1.5.0/all-in-one.yaml
    kubectl apply -f ./templates
}

function down() {
    kubectl delete -f ./templates
    kubectl delete -f https://download.elastic.co/downloads/eck/1.5.0/all-in-one.yaml
}


if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi