#!/bin/bash
COMMAND=$1
PROFILE=$2

_Values_host_name=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` && [ -z "$_Values_host_name" ] && echo "Hostname is empty" && exit



function up() {
    helm repo add grafana https://grafana.github.io/helm-charts > /dev/null

    helm install loki --create-namespace grafana/loki-stack --namespace=monitoring --version v2.8.9 --set grafana.enabled=true,prometheus.enabled=false,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=false
    helm install grafana grafana/grafana --namespace=monitoring --version 6.57.0 -f ./values.yaml --set ingress.hosts[0]=$_Values_host_name,ingress.tls[0].hosts[0]=$_Values_host_name
}

function down() {
    helm uninstall loki --namespace=monitoring
    helm uninstall grafana --namespace=monitoring
}


if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi

#Sample query: {namespace="example-tenant-5a2f",container="callee-service-application"}
