apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-config
data:
  #application
  TZ: Europe/Berlin
  server.port: "${_Values_service_port}"
  server.tomcat.threads.max: "20"

  server.forward-headers-strategy: FRAMEWORK

  #security
#  security.authentication.type: "keycloak"
#  keycloak.auth-server-url: "http://keycloak-application.oidc:8080/auth/"

  #oauth
  security.authentication.type: "oauth2"
  spring.security.oauth2.client.provider.keycloak.authorization-uri: "https://${_Values_host_name}/oidc/auth/realms/goafabric/protocol/openid-connect/auth"

  spring.security.oauth2.client.provider.keycloak.token-uri: "http://keycloak-application.oidc:8080/auth/realms/goafabric/protocol/openid-connect/token"
  spring.security.oauth2.client.provider.keycloak.userinfo-uri: "http://keycloak-application.oidc:8080/auth/realms/goafabric/protocol/openid-connect/userinfo"

#  spring.security.oauth2.client.registration.keycloak.redirect-uri: "https://${_Values_host_name}/${_Values_ingress_name}/login/oauth2/code/keycloak"

  #monitoring
  management.endpoint.health.show-details: always
  management.endpoints.web.exposure.include: "health,heapdump,circuitbreakers,prometheus"

  #zipkin/jaeger
  spring.zipkin.service.name: "callee-service-tenant-${_Values_tenant_id}"

  spring.zipkin.baseUrl: "http://zipkin.monitoring:9411"
  spring.sleuth.enabled: "true"
  spring.zipkin.enabled: "true"
#  spring.sleuth.sampler.probability: "1"

---

apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-config-external
data:



