#!/bin/bash

helm repo add example-infra https://goafabric.github.io/example-konstruction-kit/helm/charts/infra/infra
helm repo update

function helm_install() {
  helm install $1 example-infra/$1  \
  --version $2 \
  --namespace=$NAMESPACE \
  --set image.arch=`kubectl version | grep "Server Version" | grep "linux/arm64" > /dev/null && echo "-arm64v8"` \
  --set ingress.hosts=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default`
}

HOST=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default`

NAMESPACE=monitoring

#loki
helm repo add grafana https://grafana.github.io/helm-charts
#helm install loki grafana/loki-stack --namespace=$NAMESPACE --version v2.5.0 --set grafana.enabled=false,prometheus.enabled=false,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=false
#helm install grafana grafana/grafana --namespace=$NAMESPACE --version 6.17.6 -f ./values.yaml --set ingress.hosts[0]=kubernetes

#jaeger
helm_install jaeger-all 1.24.0
