#!/bin/bash

HOST=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default`

helm repo add example-infra https://goafabric.github.io/example-konstruction-kit/helm/charts/infra/infra
#helm repo update

function helm_install() {
  helm install $1 example-infra/$1  \
  --version $2 \
  --namespace=$NAMESPACE \
  --set image.arch=`kubectl version | grep "Server Version" | grep "linux/arm64" > /dev/null && echo "-arm64v8"` \
  --set ingress.hosts=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default`
}


NAMESPACE=monitoring

#welcome
helm_install welcome-board 1.0.0

#jaeger
#helm_install jaeger-all 1.24.0

#loki
helm repo add grafana https://grafana.github.io/helm-charts
helm install loki grafana/loki-stack --namespace=monitoring --version v2.5.0 --set grafana.enabled=false,prometheus.enabled=false,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=false
#helm install grafana grafana/grafana --namespace=monitoring --version 6.17.6 --set ingress.hosts[0]=$HOST,ingress.tls[0].hosts[0]=$HOST -f - <<EOF
helm install grafana grafana/grafana --namespace=monitoring --version 6.17.6 --set ingress.hosts[0]=$HOST,ingress.tls[0].hosts[0]=$HOST -f ./values.yaml