{
 "title": "MyDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Application", "query": { "query": "label_values(jvm_info,app)" } }
  ]
 },
 "panels": [
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App Start Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_started_time_seconds{app=\"$Application\"}",
     "legendFormat": "__auto",
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{app=\"$Application\", area=\"heap\", id=\"eden space\"} / 1024 / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Threads",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{app=\"$Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log  Warnings",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{app=\"$Application\"} |= `WARN`"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Max Request (ms)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(http_server_requests_seconds_max{app=\"$Application\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Request (ms)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(http_server_requests_seconds_max{app=\"$Application\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Topic Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globaltopiccount_value",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}