#!/bin/bash
source ../.values
COMMAND=$1

if [ "${COMMAND}" = "init" ]
then
    kubectl apply -f ./templates
#    ./namespace-manager create
elif [ "${COMMAND}" = "prune-force" ]
then
    kubectl delete -f ./templates
 #   ./namespace-manager delete
else
    echo Doing nothing !
fi