#!/bin/bash
COMMAND=$1
PROFILE=$2

[ ! -f "/usr/local/bin/helm" ] && echo "helm not found in /usr/local/bin, cannot continue" && exit


function up() {
    helm install jaeger-all ./ --namespace=monitoring --version 1.29.0 \
    --set ingress.hosts=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` 
}

function down() {
    helm uninstall jaeger-all --namespace=monitoring
}


if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi
