apiVersion: v1
entries:
  callee-service-application:
  - apiVersion: v2
    appVersion: 3.1.1
    created: "2023-11-04T16:55:45.65289+01:00"
    description: callee-service-application
    digest: 7157b3fdfc3df319f95d515ba7d9b57f59f8a32989c1aacaafad0c07f3bb1e86
    name: callee-service-application
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/spring/callee-service-application-1.1.1.tgz
    version: 1.1.1
  catalog-application:
  - apiVersion: v2
    appVersion: 1.0.4
    created: "2023-11-04T16:55:45.653109+01:00"
    description: catalog-application
    digest: 8c3cb57e01881c5e9a28a63bb25853762a0429a728a6719035a1fa137ac31067
    name: catalog-application
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/spring/catalog-application-1.1.1.tgz
    version: 1.1.1
  catalog-batch:
  - apiVersion: v2
    appVersion: 1.0.4
    created: "2023-11-04T16:55:45.653311+01:00"
    description: catalog-batch
    digest: c78e838ac951fadec9b66904d8c614a9740cc590e1522d17e69e725d00a37e14
    name: catalog-batch
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/spring/catalog-batch-1.1.1.tgz
    version: 1.1.1
  core-application:
  - apiVersion: v2
    appVersion: 1.0.5-vaadin-fixed-SNAPSHOT
    created: "2023-11-04T16:55:45.653535+01:00"
    description: core-application
    digest: 2056853ffefe3934adc4e43b23f36af42c87303944b1269f18582ed64b5a80ed
    name: core-application
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/spring/core-application-1.1.1.tgz
    version: 1.1.1
  core-postgres:
  - apiVersion: v2
    appVersion: "16.0"
    created: "2023-11-04T16:55:45.653705+01:00"
    description: core-postgres
    digest: 89d040b3ba8dec2e4b5b279bd1c3d2775a015da022aa7dfdf2c413cd993a5051
    name: core-postgres
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/spring/core-postgres-1.1.1.tgz
    version: 1.1.1
  person-service-application:
  - apiVersion: v2
    appVersion: 3.1.1
    created: "2023-11-04T16:55:45.653915+01:00"
    description: person-service-application
    digest: adfc02e6bc88056f26f20e218ed3756065868b046a78c6a3cde0c5536b117baa
    name: person-service-application
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/spring/person-service-application-1.1.1.tgz
    version: 1.1.1
  person-service-batch:
  - apiVersion: v2
    appVersion: 3.0.7
    created: "2023-11-04T16:55:45.654083+01:00"
    description: person-service-batch
    digest: b2f210b62dd794590bfb9ebbde26505ccf8985b3709aac1da5a2e7a1eddc2230
    name: person-service-batch
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/spring/person-service-batch-1.1.1.tgz
    version: 1.1.1
  person-service-postgres:
  - apiVersion: v2
    appVersion: "16.0"
    created: "2023-11-04T16:55:45.654298+01:00"
    description: person-service-postgres
    digest: 57c96b08cfeb7c6ad35a5a14ed811545ba691244f8e0c5b6a469d650188f25d7
    name: person-service-postgres
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/spring/person-service-postgres-1.1.1.tgz
    version: 1.1.1
  s3-minio:
  - apiVersion: v2
    appVersion: RELEASE.2023-08-23T10-07-06Z
    created: "2023-11-04T16:55:45.654505+01:00"
    description: s3-minio
    digest: 0e18eef19654d8cd08dfd603fa1eebdba1d95b424fe9cdf0c62196d47ff5520d
    name: s3-minio
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/spring/s3-minio-1.1.1.tgz
    version: 1.1.1
  welcome-board:
  - apiVersion: v2
    appVersion: 1.20.2
    created: "2023-11-04T16:55:45.654696+01:00"
    description: welcome-board
    digest: 82deac74418bdf5de86bd7452b45033a1657ae96da52bfd00808af742aee950a
    name: welcome-board
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/spring/welcome-board-1.1.1.tgz
    version: 1.1.1
generated: "2023-11-04T16:55:45.652568+01:00"
