version: "3.7"

services:
  oauth2-proxy:
    container_name: ${_Values_root_name}-oauthproxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    command:
      - --email-domain=*
#      - --scope "user:email"
    restart: 'no'
    ports:
      - "4180:4180"
    environment:
      #application
      TZ: Europe/Berlin

      # oauth2proxy generic config
      OAUTH2_PROXY_UPSTREAM: "file:///dev/null"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"

      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"

      # oauth2proxy provider config
      OAUTH2_PROXY_PROVIDER: "github"
      OAUTH2_PROXY_CLIENT_ID: "028cf7cd4281313938a0"
      OAUTH2_PROXY_SCOPE: "user:email"

      # secrets
      OAUTH2_PROXY_CLIENT_SECRET: "2d79fbf8d9a4f1c0861fc8aa5b41d835d760212b"
      # docker run -ti --rm python:3-alpine python -c 'import secrets,base64; print(base64.b64encode(base64.b64encode(secrets.token_bytes(16))));'
      OAUTH2_PROXY_COOKIE_SECRET: SvJIUgqBKxOYSxJwFREiOg==

      # urls
      OAUTH2_PROXY_REDIRECT_URL: "http://localhost:4180/oauth2/callback"


    networks:
      - ${_Values_root_name}-net


volumes:
    tmp:
    applogs:
    pgdata:

networks:
  github-net:
    driver: bridge