#!/bin/bash
COMMAND=$1
_Values_host_name=$2

function delete_secret() {
    kubectl delete secret --ignore-not-found server-certificate-secret --namespace default
}

function create_secret() {
    delete_secret $1
    kubectl create secret tls server-certificate-secret --cert=./config/server.pem --key=./config/server.key --namespace default
    kubectl annotate secret server-certificate-secret kubed.appscode.com/sync="" --namespace default
}

if [ "${COMMAND}" = "create" ]
then
    ./generate-server ${_Values_host_name}
    create_secret

elif [ "${COMMAND}" = "delete" ]
then
    delete_secret
else
    echo Doing nothing !
fi