apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  #keycloak admin user
  KEYCLOAK_ADMIN: "YWRtaW4="
  KEYCLOAK_ADMIN_PASSWORD: "YWRtaW4="

  #database user
  KC_DB_USERNAME: "a2V5Y2xvYWs="
  KC_DB_PASSWORD: "a2V5Y2xvYWs="