apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #application
  TZ: Europe/Berlin
  server.port: "{{ .Values.service.port }}"
  server.tomcat.threads.max: "20"
  server.forward-headers-strategy: FRAMEWORK

  server.max-http-request-header-size: "10KB" #required for Gateway OIDC
  server.tomcat.max-http-response-header-size: "10KB"

  process.autostart: "false"

  #security
  security.authentication.enabled: "true"

  #monitoring
  management.endpoints.web.exposure.include: "health,circuitbreakers,prometheus"
  management.endpoint.health.show-details: never
  springdoc.swagger-ui.path: "//"
  springdoc.api-docs.path: "//"

  #tracing
  spring.application.name: "{{ include "application.fullname" . }}.{{ .Release.Namespace }}"
  management.otlp.tracing.endpoint: "http://tempo.monitoring:4318/v1/traces"
  management.tracing.sampling.probability: "1.0"

  #adapter
  adapter.coreservice.url: "http://core-application.core:8080"
  adapter.catalogservice.url: "http://catalog-application.core:8080"
  adapter.timeout: "10000"