apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #application
  TZ: Europe/Berlin
  server.port: "{{ .Values.service.port }}"
  server.tomcat.threads.max: "20"
  server.forward-headers-strategy: FRAMEWORK

  server.max-http-request-header-size: "10KB" #required for Gateway OIDC
  server.tomcat.max-http-response-header-size: "10KB"

  process.autostart: "false"

  #security
  security.authentication.enabled: "false"

  #monitoring
  management.endpoints.web.exposure.include: "health,circuitbreakers,prometheus"
  management.endpoint.health.show-details: never
  springdoc.swagger-ui.path: "//"
  springdoc.api-docs.path: "//"

  #tracing
  spring.application.name: "{{ include "application.fullname" . }}.{{ .Release.Namespace }}"
  management.otlp.tracing.endpoint: "http://tempo.grafana:4318/v1/traces"
  management.tracing.sampling.probability: "1.0"

  #cache
  spring.profiles.active: "redis"

  {{ if eq .Values.cache.type "redis" }}
  spring.data.redis.sentinel.master: "master"
  spring.data.redis.sentinel.nodes: "redis.invoice:26379"
  spring.data.redis.sentinel.password: "${spring.data.redis.password}"
  {{ else }}
  spring.data.redis.host: "dragonfly.invoice"
  spring.data.redis.port: "6379"
  {{ end }}

  #adapter
  adapter.coreservice.url: "http://core-application.core:8080"
  adapter.catalogservice.url: "http://catalog-application.core:8080"
  adapter.timeout: "10000"

  #s3
  spring.cloud.aws.s3.endpoint: {{ .Values.s3.endpoint }}

  #resilience4j
  resilience4j.circuitbreaker.configs.default.slowCallDurationThreshold: "10000"
  resilience4j.circuitbreaker.configs.default.slowCallRateThreshold: "100"
  resilience4j.circuitbreaker.configs.default.failureRateThreshold: "50"
  resilience4j.circuitbreaker.configs.default.waitDurationInOpenState: "30s"
  resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls: "5"
  resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState: "10"

  resilience4j.retry.configs.default.maxAttempts: "2"
  resilience4j.retry.configs.default.waitDuration: "2s"
  resilience4j.retry.configs.default.enableExponentialBackoff: "true"
  resilience4j.retry.configs.default.exponentialBackoffMultiplier: "2"