apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #application
  TZ: Europe/Berlin
  quarkus.http.port: "{{ .Values.service.port }}"
  quarkus.http.io-threads: "20"

  #apisix oidc
  quarkus.http.limits.max-header-size: "10K"

  #tracing
  quarkus.otel.exporter.otlp.traces.endpoint: "http://tempo.grafana:4317"
  quarkus.application.name: {{ include "application.fullname" . }}.{{ .Release.Namespace }}

  #process
  process.autostart: "false"

  #security
  security.authentication.enabled: "false"

  {{ if eq .Values.cache.type "redis" }}
  spring.data.redis.sentinel.master: "master"
  spring.data.redis.sentinel.nodes: "redis.invoice:26379"
  spring.data.redis.sentinel.password: "${spring.data.redis.password}"
  {{ else }}
  spring.data.redis.host: "dragonfly.invoice"
  spring.data.redis.port: "6379"
  {{ end }}

  #adapter
  adapter.coreservice.url: "http://core-application.core:8080"
  adapter.catalogservice.url: "http://catalog-application.core:8080"
  adapter.timeout: "10000"

  #azure blob
  quarkus.azure.storage.blob.enabled: "true"
  azure.storage.blob.container-name: "invoice"
  quarkus.azure.storage.blob.connection-string: DefaultEndpointsProtocol=http;AccountName=${azure.storage.blob.account-name};AccountKey=${azure.storage.blob.account-key};BlobEndpoint=http://azurite.data:10000/${azure.storage.blob.account-name}
