apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "application.fullname" . }}-redirect
spec:
  parentRefs:
    - name: apisix
      namespace: ingress-apisix
      sectionName: http
  hostnames:
    - {{ .Values.ingress.hosts }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.ingress.paths }}
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "application.fullname" . }}
spec:
  parentRefs:
    - name: apisix
      namespace: ingress-apisix
      sectionName: https
  hostnames:
    - {{ .Values.ingress.hosts }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.ingress.paths }}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
        - type: ExtensionRef
          extensionRef:
            group: apisix.apache.org
            kind: PluginConfig
            name: {{ include "application.fullname" . }}-oidc
      backendRefs:
        - name: {{ include "application.fullname" . }}
          port:  {{ .Values.service.port }}

---
apiVersion: apisix.apache.org/v1alpha1
kind: PluginConfig
metadata:
  name: {{ include "application.fullname" . }}-oidc
spec:
  plugins:
    - name: openid-connect
      config:
        _meta:
          disable: {{ not .Values.oidc.enabled }}
        client_id: oauth2-proxy
        client_secret: none
        discovery: https://{{ .Values.ingress.hosts }}/oidc/realms/tenant-0/.well-known/openid-configuration
        access_token_in_authorization_header: false
        set_id_token_header: false
        set_userinfo_header: true
        ssl_verify: false
        redirect_uri: "{{ .Values.ingress.paths }}/redirect_uri"
        logout_path: "{{ .Values.ingress.paths }}/logout"
        session:
          secret: "{{ .Values.oidc.session.secret | default "" }}"