apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ .Release.namespace }}
spec:
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "application.fullname" . }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
