apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  spring.cloud.aws.credentials.access-key: "bWluaW9hZG1pbg=="
  spring.cloud.aws.credentials.secret-key: {{ .Values.s3.password | b64enc }}

  spring.data.redis.password: {{ .Values.redis.password | b64enc }}
  spring.data.redis.sentinel.password: {{ .Values.redis.password | b64enc }}
