apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  spring.data.redis.password: {{ .Values.redis.password | b64enc }}

  {{ if eq .Values.cache.type "redis" }}
  spring.data.redis.sentinel.password: {{ .Values.redis.password | b64enc }}
  {{ end }}
