apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
#    server: https://acme-v02.api.letsencrypt.org/directory
    email: yourname@email.com
    privateKeySecretRef:
      name: account-key
    solvers:
      - http01:
          ingress:
            class: kong

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ca
  namespace: cert-manager
spec:
  secretName: root-certificate
  issuerRef:
    name: my-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.hosts}}


