#!/bin/bash
COMMAND=$1
PROFILE=$2



kubectl version | grep "Server Version" | grep "linux/arm64" > /dev/null && _Values_server_arch="-arm64v8"

function up() {
    helm repo update
    helm repo add appscode https://charts.appscode.com/stable/ > /dev/null
    helm install kubed appscode/kubed --version v0.12.0 --namespace kube-system
}

function down() {
    helm uninstall kubed --namespace kube-system
}


if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi

