#!/bin/bash
COMMAND=$1
PROFILE=$2



kubectl version --output=json | grep "linux/arm64" > /dev/null && _Values_server_arch="-arm64v8"

function up() {
    helm repo add appscode https://charts.appscode.com/stable/ > /dev/null
    #helm repo update
    helm install kubed appscode/kubed --version v0.12.0 --namespace kube-system --create-namespace
}

function down() {
    helm uninstall kubed --namespace kube-system
}


if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi

