#!/bin/bash

#REGISTRIES=("registry-1.docker.io")
CREDENTIALS='admin:$apr1$opP9IMT.$3sY/kXyTRUvYcYrvkrcM5.' #htpasswd -n admin

KUBED_VERSION=v0.12.0
INGRESS_VERSION=4.2.3
DASHBOARD_VERSION=5.11.0

[ ! -f "/usr/local/bin/kubectl" ] && echo "kubectl not found in /usr/local/bin" && read -p "Press any key if you are stubborn enough to continue"
[ ! -f "/usr/local/bin/helm" ] && echo "helm not found in /usr/local/bin" && read -p "Press any key if you are stubborn enough to continue"

function install_secret_syncer() {
    echo __installing secret syncer ...
    helm repo add appscode https://charts.appscode.com/stable/ > /dev/null && helm repo update > /dev/null
    helm upgrade --install kubed appscode/kubed --version $KUBED_VERSION --namespace kube-system --create-namespace > /dev/null
}

function install_authentication() {
    echo __installing basic authentication
    kubectl delete secret --ignore-not-found authentication-secret --namespace default
    kubectl create secret generic authentication-secret --from-literal=auth=${CREDENTIALS} --namespace default
    kubectl annotate secret authentication-secret kubed.appscode.com/sync="" --namespace default
}

function install_certificate() {
    echo __installing server certificate
    (cd ./03_certificate; ./stack init; cd ..)
}

function install_registry() {
    [ -z "$REGISTRIES" ] && return
    echo We now need the credentials to login to the docker registry
    read -p "email: " EMAIL < /dev/tty
    read -s -p "password: " PASSWORD < /dev/tty

    for registry in ${REGISTRIES[@]}; do
        kubectl --namespace default delete secret --ignore-not-found docker-registry "$registry"-secret
        kubectl --namespace default create secret docker-registry "$registry"-secret \
                --docker-server=$registry --docker-username=$EMAIL --docker-password=$PASSWORD --docker-email=$EMAIL
        kubectl annotate secret "$1"-secret kubed.appscode.com/sync="" --namespace default
    done
}

function install_ingress() {
    echo __installing ingress controller ... this may take a moment ...
    if ! kubectl get nodes | grep -q docker-desktop; then echo no docker desktop detected, please install ingress controller yourself; return; fi
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx > /dev/null && helm repo update > /dev/null
    helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx --wait --namespace ingress-nginx --create-namespace --version $INGRESS_VERSION > /dev/null
}

function install_dashboard()  {
    echo __installing kubernetes dashboard
    _Values_host_name=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` && [ -z "$_Values_host_name" ] && echo "Hostname is empty" && exit
    helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/ > /dev/null && helm repo update > /dev/null

cat <<EOF | helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --namespace monitoring --create-namespace --version $DASHBOARD_VERSION --set ingress.hosts[0]=$_Values_host_name,ingress.tls[0].hosts[0]=$_Values_host_name  --values -
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-secret: authentication-secret
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/rewrite-target: /\$1
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  paths:
    - /dashboard/?(.*)
  tls:
    - secretName: "server-certificate-secret"
extraArgs:
  - --enable-skip-login
metrics-server:
  enabled: true
  args:
    - --kubelet-insecure-tls
metricsScraper:
  enabled: true
EOF

cat <<EOF | kubectl apply -f -
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubernetes-dashboard
    namespace: monitoring
EOF

}

function uninstall_secret_syncer() {
    helm uninstall kubed --namespace kube-system
}

function uninstall_authentication() {
    kubectl delete secret --ignore-not-found authentication-secret --namespace default
}

function uninstall_certificate() {
    (cd ./03_certificate; ./stack prune; cd ..)
}

function uninstall_ingress() {
    helm uninstall ingress-nginx --namespace ingress-nginx
}

function uninstall_registry() {
    for registry in ${REGISTRIES[@]}; do
        kubectl --namespace default delete secret --ignore-not-found docker-registry "$registry"-secret
    done
}

function uninstall_dashboard() {
    helm uninstall kubernetes-dashboard --namespace=monitoring
}

function install() {
    install_secret_syncer

    install_authentication
    install_certificate
    install_registry

    #install_ingress
    install_dashboard

    if ! kubectl get secrets -n kube-system | grep -secret; then echo secret sync failed! cluster may not work correctly; fi
    echo finished ...
}

function uninstall() {
    uninstall_secret_syncer
    uninstall_authentication
    uninstall_certificate
    uninstall_registry

    uninstall_dashboard
    uninstall_ingress

    kubectl delete ns ingress-nginx && kubectl delete ns monitoring
}

function dashboard() {
    open http://localhost:8001/api/v1/namespaces/monitoring/services/https:kubernetes-dashboard:https/proxy/ && kubectl proxy
}

if   [ "$1" = "init" ] ; then install;
elif [ "$1" = "prune" ] ; then uninstall;
elif [ "$1" = "dashboard" ] ; then dashboard;

else echo Doing nothing !; fi