#!/bin/bash
source ../.values
COMMAND=$1
SECRET_FILE=$2

[ -z "$SECRET_FILE" ] && echo variable not set && exit

function delete_secret() {
    kubectl delete secret --ignore-not-found authentication-secret -n $1
}

function create_secret() {
    delete_secret $1
    kubectl create secret generic authentication-secret --from-file=${SECRET_FILE} -n $1
}

if [ "${COMMAND}" = "create" ]
then
    for val in ${namespaces_all[@]}; do
        if kubectl get --ignore-not-found namespace $val | grep -q Active; then echo namespace: $val && create_secret $val; fi
    done
elif [ "${COMMAND}" = "delete" ]
then
    for val in ${namespaces_all[@]}; do
        if kubectl get --ignore-not-found namespace $val | grep -q Active; then echo namespace: $val && delete_secret $val; fi
    done
else
    echo Doing nothing !
fi