#!/bin/bash
COMMAND=$1
OPTS=$2

function up() {
    kubectl create configmap welcome-board-data-files --from-file=./data/ -n welcome #-o yaml > ./templates/configdata.yaml

    helm install \
    --set image.arch=`kubectl version | grep "Server Version" | grep "linux/arm64" > /dev/null && echo "-arm64v8"` \
    --set ingress.hosts=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` \
    --namespace `cat ./values.yaml | grep "namespace" | cut -d':' -f2 | xargs` \
    `cat ./Chart.yaml | grep "name" | cut -d':' -f2 | xargs` ./
}

function down() {
    kubectl delete configmap welcome-board-data-files -n welcome
    helm uninstall \
    --namespace `cat ./values.yaml | grep "namespace" | cut -d':' -f2 | xargs` \
    `cat ./Chart.yaml | grep "name" | cut -d':' -f2 | xargs`
}

if   [ "${COMMAND}" = "up" ]; then up;
elif [ "${COMMAND}" = "down" ]; then down;
elif [ "${COMMAND}" = "restart" ]; then down && up;
elif [ "${COMMAND}" = "lint" ]; then helm lint ./;

else echo Doing nothing !; fi