apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "application.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
        {{- end }}

      {{ if .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          envFrom:
            - configMapRef:
                name: {{ include "application.fullname" . }}-config
            - secretRef:
                name: {{ include "application.fullname" . }}-secret

          args: ["postgres",
                 "-c", "shared_preload_libraries=pg_stat_statements",
                 "-c", "shared_buffers={{ .Values.resources.requests.memory }}B",
                 "-c", "max_connections={{ .Values.postgres.maxConnections }}"]
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"

          readinessProbe:
            exec:
              command: ['sh', '-c', 'pg_isready']
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            exec:
              command: ['sh', '-c', 'pg_isready']
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 3

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: pgdata
              name: {{ include "application.fullname" . }}-volume

            - mountPath: /docker-entrypoint-initdb.d/
              name: {{ include "application.fullname" . }}-initdb-volume

      volumes:
        - name: {{ include "application.fullname" . }}-volume
          persistentVolumeClaim:
            claimName: {{ include "application.fullname" . }}-pvc

        - name: {{ include "application.fullname" . }}-initdb-volume
          configMap:
            name: {{ include "application.fullname" . }}-config-files
