replicaCount: 1

tenantId: 0
ingress:
  paths: /oidc
  enabled: true
  authentication: none

image:
  repository: "quay.io/keycloak/keycloak"
  pullPolicy: IfNotPresent
  pullSecrets:

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "true"

resourcesAnnotations:
  resources:
    requests:
      memory: 256M
      cpu: 250m


readinessProbe:
  initialDelaySeconds: 15

service:
  type: ClusterIP
  port: 8080

initContainers:
  - name: check-db-ready
    image: postgres:16.1
    command: ['sh', '-c','until pg_isready -h keycloak-postgres -p 5432;do echo waiting for database; sleep 1; done;']