#!/bin/bash
COMMAND=$1
IMAGE_ARCH=$2

SERVER_ARCH=`kubectl version --output=json | grep "linux/arm64" > /dev/null && echo "-arm64v8"`
[[ "${IMAGE_ARCH}" = "-native" ]] && IMAGE_ARCH+=${SERVER_ARCH}
[[ `kubectl get configmaps authentication-config --ignore-not-found -o jsonpath='{.data.authentication}' -n default` = "oidc" ]] && INGRESS_AUTHENTICATION="--set ingress.authentication=oidc"

function up() {
    helm install postgresql oci://registry-1.docker.io/bitnamicharts/postgresql \
    --version 16.5.2 \
    --namespace example \
    --set global.postgresql.auth.database=main \
    --set global.postgresql.auth.username=main \
    --set global.postgresql.auth.password=postgres > /dev/null
}

function down() {
    helm uninstall postgresql --namespace example
    kubectl delete pvc -l app.kubernetes.io/name=postgresql -n example
}


if   [ "${COMMAND}" = "up" ]; then up;
elif [ "${COMMAND}" = "down" ]; then down;
elif [ "${COMMAND}" = "restart" ]; then down && up;
elif [ "${COMMAND}" = "lint" ]; then helm lint ./;

else echo Doing nothing !; fi