replicaCount: 1
maxReplicas: 3

ingress:
  paths: /core

image:
  repository: "goafabric/core-service"
  pullPolicy: IfNotPresent #Always
  pullSecrets:
  arch: "-native"

resourcesAnnotations:
  resources:
    requests:
      memory: 256M
      cpu: 250m

  command: ["java", "-Xms256M", "-Xmx256M", "-cp", "/app/resources:/app/classes:/app/libs/*",
            "org.goafabric.core.Application"]

nativeAnnotations:
  resources:
    requests:
      memory: 64M
      cpu: 250m

  args: ["-Xmx92M"]

readinessProbe:
  initialDelaySeconds: 5

service:
  type: ClusterIP
  port: 8080

postgresql:
  host: postgresql.data

s3:
  endpoint: "http://s3-minio.data:9000"

kafka:
  enabled:
  server: "kafka.data"
  port: "9092"

initContainers:
  - name: check-db-ready
    image: postgres:17.5
    command: ['sh', '-c','until pg_isready -h {{ .Values.postgresql.host }} -p 5432;do echo waiting for database; sleep 1; done;']

oidc:
  enabled:


multiTenancy:
  tenants: "0,5"