#!/bin/bash
COMMAND=$1
PROFILE=$2

if ! kubectl get nodes | grep -q docker-desktop
then
    echo non docker desktop environment detected ... applying ingress class
    kubectl apply -f ./template/nginx-ingress-class.yaml
    exit
else
    echo docker desktop detected, installing ingress controller ...
fi

function up() {
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx > /dev/null
    helm install ingress-nginx ingress-nginx/ingress-nginx --wait --namespace ingress-nginx --create-namespace --version 4.2.3
    echo waiting for
    #kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.3.0/deploy/static/provider/cloud/deploy.yaml
}

function down() {
    helm uninstall ingress-nginx --namespace ingress-nginx
    #kubectl delete -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.3.0/deploy/static/provider/cloud/deploy.yaml
}


if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi

#Sample query: {namespace="example-tenant-5a2f",container="callee-service-application"}
