#!/bin/bash
COMMAND=$1
PROFILE=$2

if ! kubectl get nodes | grep -q docker-desktop; then exit; fi

function up() {
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx > /dev/null
    helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace --version 4.0.13
}

function down() {
    helm uninstall ingress-nginx --namespace ingress-nginx
}


if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi

#Sample query: {namespace="example-tenant-5a2f",container="callee-service-application"}
