#!/bin/bash
export COMMAND=$1

if [ "${COMMAND}" = "up" ]
then
    docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
    docker-compose -f ./templates/docker-compose.yml up -d
elif [ "${COMMAND}" = "down" ]
then
    docker-compose -f ./templates/docker-compose.yml down
    docker plugin disable loki --force
elif [ "${COMMAND}" = "restart" ]
then
    docker-compose -f ./templates/docker-compose.yml down
    docker-compose -f ./templates/docker-compose.yml up
else
    echo Doing nothing !
fi
