apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  spring.rabbitmq.username: "YWRtaW4="
  spring.rabbitmq.password: {{ .Values.messageBroker.password | b64enc }}

  spring.kafka.username: "YWRtaW4="
  spring.kafka.password: {{ .Values.messageBroker.password | b64enc }}