# templates/apisixroute.yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ include "application.fullname" . }}-{{ .Values.ingress.tenantID }}
spec:
  http:
    - name: {{ include "application.fullname" . }}-{{ .Values.ingress.tenantID }}
      match:
        hosts:
          - {{ .Values.ingress.hosts }}
        paths:
          - {{ .Values.ingress.paths }}/{{ .Values.ingress.tenantID }}
          - {{ .Values.ingress.paths }}/{{ .Values.ingress.tenantID }}/*
      backends:
          - serviceName: {{ include "application.fullname" . }}
            servicePort: http
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true
        - name: openid-connect
          enable: true
          config:
            client_id: oauth2-proxy
            client_secret: none
            discovery: https://{{ .Values.ingress.hosts }}/oidc/realms/tenant-{{ .Values.ingress.tenantID }}/.well-known/openid-configuration
            access_token_in_authorization_header: false
            set_id_token_header: false
            set_userinfo_header: false
            ssl_verify: false
            redirect_uri: "/core/{{ .Values.ingress.tenantID }}/redirect_uri"

---

# values.yaml
ingress:
  enabled: true
  tenantIDs:
    - 0
    - 5
    - 1
    # Add more tenant IDs as needed

---

{{- if .Values.ingress.enabled }}
  {{- range $tenantID := .Values.ingress.tenantIDs }}
  {{- include "my-chart-name.templates.apisixroute" (dict "Values" . "application" .) | indent 2 }}
  {{- end }}
  {{- end }}
