# values.yaml or custom configuration file
ingress:
  enabled: true
  hosts:
    - myexample.com
  paths:
    - /0
    - /5
    - /1


---

  {{- if .Values.ingress.enabled }}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ include "application.fullname" . }}-{{ .Values.ingress.tenantID }}
spec:
  http:
    - name: {{ include "application.fullname" . }}-{{ .Values.ingress.tenantID }}
      match:
        hosts:
          - {{ .Values.ingress.hosts}}
        paths:
          - {{ printf "/%d" .Values.ingress.tenantID }}
          - {{ printf "/%d/*" .Values.ingress.tenantID }}
      backends:
        - serviceName: {{ include "application.fullname" . }}
          servicePort: http
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true
        - name: openid-connect
          enable: true
          config:
            client_id: oauth2-proxy
            client_secret: none
            discovery: {{ printf "https://%s/oidc/realms/tenant-%d/.well-known/openid-configuration" .Values.ingress.hosts .Values.ingress.tenantID }}
            access_token_in_authorization_header: false
            set_id_token_header: false
            set_userinfo_header: false
            ssl_verify: false
            redirect_uri: {{ printf "/core/%d/redirect_uri" .Values.ingress.tenantID }}
  {{- end }}
