#!/bin/bash
COMMAND=$1
PROFILE=$2

function up() {
    helm repo add jetstack https://charts.jetstack.io > /dev/null
    helm upgrade --install cert-manager jetstack/cert-manager --version v1.11.0 \
         --namespace cert-manager --create-namespace --set installCRDs=true,prometheus.enabled=false,extraArgs[0]='--enable-certificate-owner-ref'
    kubectl apply -f ./templates/deployment.yaml
}

function down() {
    kubectl delete --ignore-not-found -f ./templates/deployment.yaml > /dev/null
    helm uninstall cert-manager --namespace cert-manager && kubectl delete namespace cert-manager
}



if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi

#Sample query: {namespace="example-tenant-5a2f",container="callee-service-application"}
