#!/bin/bash
export COMMAND=$1

function read_secret() {
    read -p "server name <kubernetes>: " _Values_host_name < /dev/tty
    _Values_host_name="${_Values_host_name:=kubernetes}"

    if ping -c 1 "${_Values_host_name}" &> /dev/null
    then
      echo host ${_Values_host_name} reachable
    else
      echo host ${_Values_host_name} is not reachable, do have have entry inside /etc/hosts ?
      exit
    fi

    _Values_host_name="${_Values_host_name:=kubernetes}"

    kubectl delete --ignore-not-found configmap cluster-config -n default
    kubectl create configmap cluster-config -n default --from-literal=hostname=${_Values_host_name}
    _Values_host_name=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` && [ -z "$_Values_host_name" ] && echo "Server Name is empty" && exit
    echo Server Name is: ${_Values_host_name}
}

if [ "${COMMAND}" = "init" ]
then
    read_secret
    ./secret-manager create ${_Values_host_name}
elif [ "${COMMAND}" = "prune" ]
then
    ./secret-manager delete
else
    echo Doing nothing !
fi