replicaCount: 1

tenantId: 0
ingress:
  paths: /person
  enabled: true

image:
  repository: "goafabric/person-service"
  pullPolicy: IfNotPresent #Always
  pullSecrets:

resourcesAnnotations:
  resources:
    requests:
      memory: 256M
      cpu: 250m

  command: ["java", "-Xms256M", "-Xmx256M", "-cp", "/app/resources:/app/classes:/app/libs/*",
            "org.goafabric.personservice.Application"]

nativeAnnotations:
  resources:
    requests:
      memory: 64M
      cpu: 250m

  args: ["-Xmx64M"]

readinessProbe:
  initialDelaySeconds: 5

service:
  type: ClusterIP
  port: 8080

initContainers:

oidc:
  enabled:

multiTenancy:
  tenants: "0,5"
