#!/bin/bash
COMMAND=$1
PROFILE=$2

if ! kubectl get nodes | grep -q docker-desktop
then
    echo installing ingress controller ...
fi

function up() {
    helm repo add apisix https://charts.apiseven.com  > /dev/null
    helm repo add bitnami https://charts.bitnami.com/bitnami  > /dev/null
    #helm repo update

    helm install apisix apisix/apisix --version 2.3.0 \
      --set service.type=LoadBalancer,apisix.ssl.enabled=true,apisix.ssl.containerPort=443 \
      --set "apisix.plugins={opentelemetry,openid-connect,redirect,proxy-rewrite,basic-auth}" \
      --set apisix.pluginAttrs.redirect.https_port=443 \
      --set apisix.pluginAttrs.opentelemetry.resource.service.name=APISIX \
      --set apisix.pluginAttrs.opentelemetry.collector.address=otlp.monitoring:4318 \
      --set ingress-controller.enabled=true \
      --namespace ingress-apisix \
      --create-namespace \
      --set etcd.replicaCount=2 \
      --values ./values.yaml

#      --set podSecurityContext.sysctls[0].name=net.ipv4.ip_unprivileged_port_start,podSecurityContext.sysctls[0].value=1 \

#    helm install apisix-dashboard apisix/apisix-dashboard \
#      --namespace ingress-apisix

    helm install apisix-tls ./apisix-tls --set hostname=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` \
      --namespace ingress-apisix
}

function down() {
    helm uninstall apisix-tls --namespace ingress-apisix
#    helm uninstall apisix-dashboard --namespace ingress-apisix
    helm uninstall apisix --namespace ingress-apisix
}

function proxy() {
      kubectl -n ingress-apisix port-forward service/apisix-dashboard 9090:80
}

if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "prune" ]; then down;
elif [ "${COMMAND}" = "proxy" ]; then proxy;

else echo Doing nothing !; fi