apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  spring.datasource.username: cGVyc29uLXNlcnZpY2U=
  spring.datasource.password: {{ .Values.database.password | default "postgres" | b64enc }}

  quarkus.datasource.username: cGVyc29uLXNlcnZpY2U=
  quarkus.datasource.password: {{ .Values.database.password | default "postgres" | b64enc }}

  spring.security.user.name: c2VydmljZQ==
  spring.security.user.password: {{ .Values.serviceUser.password | default "secret" | b64enc }}

  adapter.calleeservice.user.name: c2VydmljZQ==
  adapter.calleeservice.user.password: {{ .Values.serviceUser.password | default "secret" | b64enc }}