apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #application
  TZ: Europe/Berlin
  server.port: "{{ .Values.service.port }}"
  server.tomcat.threads.max: "20"
  server.forward-headers-strategy: FRAMEWORK

  #security
  security.authentication.enabled: "false"

  #monitoring
  management.endpoint.health.show-details: always
  management.endpoints.web.exposure.include: "health,heapdump,circuitbreakers,prometheus"

  #zipkin/jaeger
  spring.application.name: "{{ include "application.fullname" . }}"
  management.otlp.tracing.endpoint: "http://otlp.monitoring:4318/v1/traces"
  management.tracing.sampling.probability: "1.0"
  logging.level.io.opentelemetry: "INFO"

  #rabbit
  spring.rabbitmq.host: "rabbitmq"

