apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  spring.rabbitmq.username: "YWRtaW4="
  spring.rabbitmq.password: {{ .Values.messageBroker.password | default "admin" | b64enc }}