apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #application
  TZ: Europe/Berlin

  #persistence
  spring.datasource.url: "jdbc:postgresql://person-service-postgres:5432/person"
  spring.datasource.hikari.maximum-pool-size: "10"
  spring.datasource.hikari.connection-timeout: "10000"

  database.provisioning.goals: "-import-demo-data -terminate"

  #adapter
  adapter.calleeservice.url: "http://callee-service-application.example:8080"