apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  RABBITMQ_DEFAULT_USER: "YWRtaW4="
  RABBITMQ_DEFAULT_PASS: {{ .Values.messageBroker.password | default "admin" | b64enc }}