#!/bin/bash
source ../.values
export COMMAND=$1

if [ "${COMMAND}" = "init" ]
then
    for val in ${namespaces[@]}; do
        kubectl create namespace $val
    done
elif [ "${COMMAND}" = "prune-force" ]
then
    for val in ${namespaces[@]}; do
        kubectl delete namespace $val
    done
else
    echo Doing nothing !
fi