#!/bin/bash
source ../.values
COMMAND=$1

if [ "${COMMAND}" = "init" ]
then
    ./namespace-manager create
elif [ "${COMMAND}" = "prune-force" ]
then
    ./namespace-manager delete
else
    echo Doing nothing !
fi