apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: my-cluster-issuer
    konghq.com/strip-path: 'true'
    konghq.com/plugins: {{ include "application.fullname" . }}-add-headers
spec:
  ingressClassName: kong
  tls:
    - hosts:
        - {{ .Values.ingress.hosts}}
      secretName: root-certificate
  rules:
    - host: {{ .Values.ingress.hosts}}
      http:
        paths:
          - path: {{ .Values.ingress.paths}}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "application.fullname" . }}
                port:
                  name: http

---

apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: {{ include "application.fullname" . }}-add-headers
plugin: request-transformer
config:
  add:
    headers:
      - Authorization:BASIC {{ b64enc (printf "%s:%s" ("c2VydmljZQ==" | b64dec) (.Values.service.password )) }}