apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ include "application.fullname" . }}
spec:
  http:
    - name: {{ include "application.fullname" . }}
      match:
        hosts:
          - {{ .Values.ingress.hosts }}
        paths:
          - {{ .Values.ingress.paths }}
          - {{ .Values.ingress.paths }}/*
      backends:
        - serviceName: {{ include "application.fullname" . }}
          servicePort: http
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true
        - name: openid-connect
          enable: true
          config:
            client_id: oauth2-proxy
            client_secret: none
            discovery: https://{{ .Values.ingress.hosts }}/oidc/realms/tenant-0/.well-known/openid-configuration
            access_token_in_authorization_header: false
            set_id_token_header: false
            set_userinfo_header: true
            ssl_verify: false
            redirect_uri: "{{ .Values.ingress.paths }}/redirect_uri"
            logout_path: "{{ .Values.ingress.paths }}/logout"
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - {{ .Values.ingress.paths }}/(.*)
              - /$1
            headers:
              X-TenantId: 0
        - name: serverless-post-function
          enable: true
          config:
            phase: "rewrite"
            functions:
              - "return function(conf, ctx) local core = require(\"apisix.core\"); local cjson = require(\"cjson\"); local userinfo = core.request.header(ctx, \"X-Userinfo\"); if userinfo then local decodedUserinfo = ngx.decode_base64(userinfo); local decodedUserinfoJson = cjson.decode(decodedUserinfo); core.request.add_header(\"X-Auth-Request-Preferred-Username\", decodedUserinfoJson.preferred_username); ngx.log(ngx.ERR, \"apisix function \"); end; end"