apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  spring.security.user.name: YWRtaW4=
  spring.security.user.password: c2VjcmV0
