apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  spring.security.user.name: c2VydmljZQ==
  spring.security.user.password: {{ .Values.serviceUser.password | b64enc }}
