apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  spring.security.user.name: {{ .Values.user.name | b64enc }}
  spring.security.user.password: {{ .Values.user.password | default "secret" | b64enc }}
