#!/bin/bash
COMMAND=$1
PROFILE=$2




function up() {
    helm install --create-namespace jaeger-all ./ --namespace=monitoring \
    --set ingress.hosts=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` 
}

function down() {
    helm uninstall jaeger-all --namespace=monitoring
}


if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi
