#!/bin/bash
COMMAND=$1

function up() {
    helm install \
    --set image.arch=`kubectl version | grep "Server Version" | grep "linux/arm64" > /dev/null && echo "-arm64v8"` \
    --set host.name=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` \
    `cat ./Chart.yaml | grep "name" | cut -d':' -f2 | xargs` ./
}

function down() {
    helm uninstall `cat ./Chart.yaml | grep "name" | cut -d':' -f2 | xargs`
}

if   [ "${COMMAND}" = "up" ]; then up;
elif [ "${COMMAND}" = "down" ]; then down;
elif [ "${COMMAND}" = "prune" ]; then down;
elif [ "${COMMAND}" = "restart" ]; then down && up;
elif [ "${COMMAND}" = "lint" ]; then helm lint ./;

else echo Doing nothing !; fi