#!/bin/bash
COMMAND=$1
PROFILE=$2



kubectl version --output=json | grep "linux/arm64" > /dev/null && _Values_server_arch="-arm64v8"
_Values_host_name=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` && [ -z "$_Values_host_name" ] && echo "Hostname is empty" && exit

function up() {
    helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/ > /dev/null

    helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --namespace monitoring --create-namespace --version 5.11.0 \
    --set ingress.enabled=true,ingress.className=nginx \
    --set ingress.annotations.'nginx\.ingress\.kubernetes\.io/auth-secret'=authentication-secret,ingress.annotations.'nginx\.ingress\.kubernetes\.io/auth-type'=basic,ingress.annotations.'nginx\.ingress\.kubernetes\.io/rewrite-target'='/$1' \
    --set ingress.hosts[0]=$_Values_host_name,ingress.paths[0]='/dashboard/?(.*)'\
    --set ingress.tls[0].hosts[0]=$_Values_host_name,ingress.tls[0].secretName=server-certificate-secret \
    --set metricsScraper.enabled=true,metrics-server.enabled=true \
    --set metrics-server.args[0]='--kubelet-insecure-tls',extraArgs[0]='--enable-skip-login'

    echo -n I2NyZWF0ZXMgYSByb2xlIGJpbmRpbmcgdGhhdCB0aWVzIHRoZSBTZXJ2aWNlQWNjb3VudCBjcmVhdGVkIGJ5IHRoZSBoZWxtIHNoYXJ0IHdpdGggdGhlIGV4aXN0aW5nIENsdXN0ZXJSb2xlIGZyb20geW91ciBLdWJlcm5ldGVzCiNodHRwczovL2dpdGh1Yi5jb20va3ViZXJuZXRlcy9kYXNoYm9hcmQvYmxvYi9tYXN0ZXIvZG9jcy91c2VyL2FjY2Vzcy1jb250cm9sL1JFQURNRS5tZAoKYXBpVmVyc2lvbjogcmJhYy5hdXRob3JpemF0aW9uLms4cy5pby92MQpraW5kOiBDbHVzdGVyUm9sZUJpbmRpbmcKbWV0YWRhdGE6CiAgbmFtZToga3ViZXJuZXRlcy1kYXNoYm9hcmQKICBuYW1lc3BhY2U6IG1vbml0b3JpbmcKcm9sZVJlZjoKICBhcGlHcm91cDogcmJhYy5hdXRob3JpemF0aW9uLms4cy5pbwogIGtpbmQ6IENsdXN0ZXJSb2xlCiAgbmFtZTogY2x1c3Rlci1hZG1pbgpzdWJqZWN0czoKICAtIGtpbmQ6IFNlcnZpY2VBY2NvdW50CiAgICBuYW1lOiBrdWJlcm5ldGVzLWRhc2hib2FyZAogICAgbmFtZXNwYWNlOiBtb25pdG9yaW5n \
    | base64 -d | kubectl apply -f -
#    kubectl apply -f ./dashboard-admin.yaml
}

function down() {
    helm uninstall kubernetes-dashboard --namespace=monitoring
    kubectl delete clusterrolebinding kubernetes-dashboard
#    kubectl delete -f ./dashboard-admin.yaml
}

function proxy() {
  open http://localhost:8001/api/v1/namespaces/monitoring/services/https:kubernetes-dashboard:https/proxy/ && kubectl proxy
}


if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "prune" ]; then down;
elif [ "${COMMAND}" = "proxy" ]; then proxy;

else echo Doing nothing !; fi

#Sample query: {namespace="example-tenant-5a2f",container="callee-service-application"}
