apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "application.fullname" . }}-gateway
spec:
  gatewayClassName: kong
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: {{ .Values.ingress.hosts}}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: root-certificate

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "application.fullname" . }}-route
  annotations:
    konghq.com/strip-path: 'true'
spec:
  parentRefs:
    - name: {{ include "application.fullname" . }}-gateway
      sectionName: https
  hostnames:
    - {{ .Values.ingress.hosts}}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.ingress.paths }}
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: X-TenantId
                value: "0"
              - name: Authorization
                value: BASIC {{ b64enc (printf "%s:%s" ("c2VydmljZQ==" | b64dec) (.Values.service.password )) }}
      backendRefs:
        - name: {{ include "application.fullname" . }}
          port: 8080
