#!/bin/bash
source .values

COMMAND=$1
WORKSPACE=$TF_VAR_hostname

function apply() {
  (cd $1; terraform workspace select -or-create $WORKSPACE && terraform init && terraform apply -auto-approve)
}

function destroy() {
  (cd $1; terraform workspace select -or-create $WORKSPACE && terraform destroy -auto-approve)
}

function up() {
    time(
    apply ../../infra/vault
    apply ../../core
    apply ../../event
    apply ../../invoice
    )
}

function down() {
    time(
    destroy ../../infra/vault
    destroy ../../invoice
    destroy ../../event
    destroy ../../core
    )
}

down && up