#!/bin/bash
COMMAND=$1
WORKSPACE=$TF_VAR_hostname

function apply() {
  (cd $1; terraform workspace select -or-create $WORKSPACE && terraform apply -auto-approve)
}

function destroy() {
  (cd $1; terraform workspace select -or-create $WORKSPACE && terraform destroy -auto-approve)
}

function up() {
    time(
    apply ./
    cp kind-config ~/.kube.profile/.kube.kind/config
    kubectl create configmap cluster-config -n default --from-literal=hostname=$TF_VAR_hostname
    apply ../../infra/ingress
    apply ../../infra/monitoring
    )
}

function down() {
    time(
    destroy ../../infra/monitoring
    destroy ../../infra/ingress
    destroy ./
    )
}

if   [ "${COMMAND}" = "init" ]; then up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi