#!/bin/bash
source .values
COMMAND=$1
WORKSPACE="kind"

function apply() {
  (cd $1; terraform workspace select -or-create $WORKSPACE && terraform apply -auto-approve)
}

function destroy() {
  (cd $1; terraform workspace select -or-create $WORKSPACE && terraform destroy -auto-approve)
}

function up() {
    apply ./
    apply ../../infra/ingress_certs
}

function down() {
    destroy ../../infra/ingress_certs
    destroy ./
}

if   [ "${COMMAND}" = "init" ]; then up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi