apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}
stringData:
  POSTGRES_DB: core
data:
  POSTGRES_USER: Y2F0YWxvZw==
  POSTGRES_PASSWORD: {{ .Values.database.password | default "postgres" | b64enc }}