apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /jaeger/$2
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    cert-manager.io/cluster-issuer: my-cluster-issuer

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.hosts}}
      secretName: root-certificate
  rules:
    - host: {{ .Values.ingress.hosts}}
      http:
        paths:
          - path: /jaeger(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: tracing
                port:
                  number: 80