apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #application
  TZ: Europe/Berlin
  quarkus.http.port: "{{ .Values.service.port }}"
  quarkus.http.io-threads: "20"

  #security
  security.authentication.enabled: "true"

  #tracing
  quarkus.otel.exporter.otlp.traces.endpoint: "http://tempo.monitoring:4317"
  quarkus.application.name: {{ include "application.fullname" . }}.{{ .Release.Namespace }}

  #persistence
  quarkus.datasource.jdbc.url: "jdbc:postgresql://person-service-postgres-postgresql-ha-pgpool:5432/person"
  quarkus.datasource.jdbc.max-size: "10"

  database.provisioning.goals: "-import-demo-data"

  #adapter
  adapter.calleeservice.url: "http://callee-service-application:8080"

  adapter.timeout: "10000"
  adapter.failureRate: "0.5"
  adapter.openDuration: "30000"
  adapter.circuitBreaker.enabled: "true"