apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  spring.datasource.username: cGVyc29uLXNlcnZpY2U=
  spring.datasource.password: {{ .Values.database.password | b64enc }}

  quarkus.datasource.username: cGVyc29uLXNlcnZpY2U=
  quarkus.datasource.password: {{ .Values.database.password | b64enc }}

  adapter.calleeservice.user: WVdSdGFXND0=
  adapter.calleeservice.password: WVdSdGFXND0=