apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  quarkus.datasource.username: cGVyc29uLXNlcnZpY2U=
  quarkus.datasource.password: {{ .Values.database.password | b64enc }}

  quarkus.security.users.embedded.users.service: {{ .Values.service.password | b64enc }}
  quarkus.security.users.embedded.roles.service: c3RhbmRhcmRfcm9sZQ==

  adapter.calleeservice.user.name: c2VydmljZQ==
  adapter.calleeservice.user.password: {{ .Values.service.password | b64enc }}