#!/bin/bash
#find . -maxdepth 1 -not -path "." -type d -exec bash -c "cd '{}' && [ -f ./stack ] && echo '{}' && ./stack $1" \;
find . -maxdepth 1 -not -path "." -type d -print0 | sort -hz | xargs -0 -I '{}' bash -c "cd '{}' && [ -f ./stack ] && echo '{}' && ./stack $1"
