#!/bin/bash
COMMAND=$1
PROFILE=$2

[ ! -f "/usr/local/bin/istioctl" ] && echo "istioctl not found in /usr/local/bin, cannot continue" && exit

_Values_host_name=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` && [ -z "$_Values_host_name" ] && echo "Hostname is empty" && exit

function init() {
    istioctl-ambient install --set profile=ambient -y
    for namespace in $(kubectl get ns | grep -vE 'default|kube|monitoring|ingress|istio|oidc' | awk '{print $1}' | tail -n +2); do
            kubectl label namespace $namespace istio.io/dataplane-mode=ambient --overwrite; done
}

function prune() {
    istioctl-ambient uninstall -y --purge
    kubectl delete namespace istio-operator && kubectl delete namespace istio-system
}

if   [ "${COMMAND}" = "init" ] ; then init;
elif [ "${COMMAND}" = "prune" ]; then prune;

else echo Doing nothing !; fi

#https://istio.io/latest/blog/2022/get-started-ambient/