apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #application
  TZ: Europe/Berlin
  quarkus.http.port: "{{ .Values.service.port }}"
  quarkus.http.io-threads: "20"

  #apisix oidc
  quarkus.http.limits.max-header-size: "10K"

  #tracing
  quarkus.otel.exporter.otlp.traces.endpoint: "http://tempo.grafana:4317"
  quarkus.application.name: {{ include "application.fullname" . }}.{{ .Release.Namespace }}

  #persistence
  quarkus.datasource.jdbc.url: "jdbc:postgresql://{{ .Values.postgresql.host }}:5432/main"
  quarkus.datasource.jdbc.max-size: "10"

  multi-tenancy.tenants: "{{ .Values.multiTenancy.tenants }}"
  multi-tenancy.schema-prefix: "core_"
  database.provisioning.goals: "-migrate -import-demo-data"

  #kafka
  kafka.bootstrap.servers: "{{ .Values.kafka.server }}:{{ .Values.kafka.port }}"
  mp.messaging.outgoing.general.enabled: "{{ .Values.kafka.enabled }}"

  mp.messaging.connector.smallrye-kafka.security.protocol: "SASL_PLAINTEXT"
  mp.messaging.connector.smallrye-kafka.sasl.mechanism: "PLAIN" #"SCRAM-SHA-512"
  mp.messaging.connector.smallrye-kafka.sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${spring.kafka.username}" password="${spring.kafka.password}";
