apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  spring.datasource.username: Y29yZQ==
  spring.datasource.password: {{ .Values.database.password | default "postgres" | b64enc }}

  spring.cloud.aws.credentials.access-key: "bWluaW9hZG1pbg=="
  spring.cloud.aws.credentials.secret-key: {{ .Values.s3.password | default "minioadmin" | b64enc }}

  spring.security.oauth2.client-id: "b2F1dGgyLXByb3h5"
  spring.security.oauth2.client-secret: "bm9uZQ=="
