apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  spring.datasource.username: Y29yZQ==
  spring.datasource.password: {{ .Values.database.password | b64enc }}

  spring.cloud.aws.credentials.access-key: "bWluaW9hZG1pbg=="
  spring.cloud.aws.credentials.secret-key: {{ .Values.s3.password | b64enc }}

  spring.security.user.name: c2VydmljZQ==
  spring.security.user.password: {{ .Values.service.password | b64enc }}
