#!/bin/bash
source ../.values
export COMMAND=$1

function delete_secret() {
    kubectl delete secret --ignore-not-found authentication-secret -n $1
}

function create_secret() {
    delete_secret $1
    kubectl create secret generic authentication-secret --from-file=./config/auth -n $1
}

if [ "${COMMAND}" = "init" ]
then
    [ ! -f "./config/auth" ] && echo please enter password for user admin && htpasswd -c ./config/auth admin

    if kubectl get --ignore-not-found namespace linkerd | grep -q Active; then create_secret linkerd; fi
    create_secret kube-system

    for val in ${namespaces[@]}; do
        create_secret $val
    done
elif [ "${COMMAND}" = "prune" ]
then
    rm ./config/auth
    if kubectl get --ignore-not-found namespace linkerd | grep -q Active; then delete_secret linkerd; fi
    delete_secret kube-system

    for val in ${namespaces[@]}; do
        delete_secret $val
    done
else
    echo Doing nothing !
fi

# htpasswd -c auth admin
# kubectl create secret generic authentication-secret --from-file=auth
# base64 auth
