#!/bin/bash
source ../.values
export COMMAND=$1

function delete_secret() {
    kubectl delete secret --ignore-not-found authentication-secret -n $1
}

function create_secret() {
    delete_secret $1 && kubectl create secret generic authentication-secret --from-file=./config/auth -n $1
}

function read_secret() {
    [ ! -f "./config/auth" ] && echo please enter password for user admin && htpasswd -c ./config/auth admin
  }

if [ "${COMMAND}" = "init" ]
then
    read_secret

    for val in ${namespaces_secret[@]}; do
        if kubectl get --ignore-not-found namespace $val | grep -q Active; then echo namespace: $val && create_secret $val; fi
    done
elif [ "${COMMAND}" = "prune" ]
then
    for val in ${namespaces_secret[@]}; do
        if kubectl get --ignore-not-found namespace $val | grep -q Active; then echo namespace: $val && delete_secret $val; fi
    done
else
    echo Doing nothing !
fi