#!/bin/bash
export COMMAND=$1

if [ "${COMMAND}" = "init" ]
then
    cp ../root/config/root.pem ./config/example-root.pem
    cp ../root/config/root.p12 ./config/example-root.p12
    ./secret-manager create
elif [ "${COMMAND}" = "prune" ]
then
    ./secret-manager delete
else
    echo Doing nothing !
fi