#!/bin/bash
COMMAND=$1
PROFILE=$2

[ ! -f "/usr/local/bin/istioctl" ] && echo "istioctl not found in /usr/local/bin, cannot continue" && exit

#kubectl version --output=json | grep "linux/arm64" > /dev/null && _Values_server_arch="-arm64v8"
_Values_host_name=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` && [ -z "$_Values_host_name" ] && echo "Hostname is empty" && exit


function init() {
#    [ "${_Values_server_arch}" = "-arm64v8" ] && _Values_hub="--hub=ghcr.io/resf/istio" && echo "arm64 detected"
    istioctl operator init ${_Values_hub} --tag=1.15.1
    kubectl apply -f ./templates/operator${_Values_server_arch}.yaml
}

function prune() {
    istioctl x uninstall -y --purge
    kubectl delete namespace istio-operator && kubectl delete namespace istio-system
#    istioctl operator remove && kubectl delete namespace istio-operator
}

if   [ "${COMMAND}" = "init" ] ; then init;
elif [ "${COMMAND}" = "prune" ]; then prune;

else echo Doing nothing !; fi