#!/bin/bash
COMMAND=$1
PROFILE=$2

[ ! -f "/usr/local/bin/istioctl" ] && echo "istioctl not found in /usr/local/bin, cannot continue" && exit

function up() {
    kubectl apply -f ./templates
}

function down() {
    kubectl delete --ignore-not-found -f ./templates
}


if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "ambient" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi