kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${_Values_app_name}-pv
  labels:
    app: ${_Values_app_name}
    type: local
spec:
  storageClassName: "standard"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/var/data"
