#TODO: do we need an extra volume definition ?
#TODO: also stack prune hangs and gives " deleting cluster-scoped resources, not scoped to the provided namespace
kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${_Values_app_name}-pv
  labels:
    app: ${_Values_app_name}
    type: local
spec:
  storageClassName: "standard" #TODO: is standard correct ?
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/var/data"
