apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}
stringData:
  POSTGRES_DB: keycloak
data:
  POSTGRES_USER: a2V5Y2xvYWs=
  POSTGRES_PASSWORD: a2V5Y2xvYWs=