apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ include "application.fullname" . }}
spec:
  http:
    - name: {{ include "application.fullname" . }}
      match:
        hosts:
          - {{ .Values.ingress.hosts}}
        paths:
          - /welcome
          - /welcome/*
      backends:
        - serviceName: welcome-board
          servicePort: 8080
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - /welcome/(.*)
              - /$1