replicaCount: 1

ingress:
  paths: /event
  enabled: true
  authentication: basic

image:
  repository: "goafabric/event-dispatcher-service"
  pullPolicy: Always #IfNotPresent
  pullSecrets: 

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "true"

resourcesAnnotations:
  resources:
    requests:
      memory: 128M
      cpu: 250m

  command: ["java", "-Xms128M", "-Xmx128M", "-cp", "/app/resources:/app/classes:/app/libs/*", "org.goafabric.eventdispatcher.Application"]

nativeAnnotations:
  resources:
    requests:
      memory: 16M
      cpu: 250m

  args: ["-Xmx16M"]

readinessProbe:
  initialDelaySeconds: 1

service:
  type: ClusterIP
  port: 8080