apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-service-postgres
spec:
  selector:
    matchLabels:
      app: country-service-postgres
  replicas: 1
  strategy:
    type: Recreate #RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: country-service-postgres
    spec:
      containers:
        - name: country-service-postgres
          image: postgres:13.1
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: country-service-postgres-secret

          args:
            - postgres
            - -c
            - shared_buffers=128MB
            - -c
            - max_connections=30
            - -c
            - shared_preload_libraries=pg_stat_statements
          resources:
            requests:
              memory: "128M"
              cpu: "250m"
            limits:
              cpu: "500m"

          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: country-service-postgres-initdb-volume
            - mountPath: /var/lib/postgresql/data
              name: country-service-postgres-pvc-volume

      volumes:
        - name: country-service-postgres-initdb-volume
          configMap:
            name: country-service-postgres-data-files
        - name: country-service-postgres-pvc-volume
          persistentVolumeClaim:
            claimName: country-service-postgres-pvc