#!/bin/bash
COMMAND=$1
PROFILE=$2

function up() {
    kubectl apply -f ./template/ingress-class.yaml
    kubectl get ingressclasses
    #kubectl edit ingressClass/nginx
}

function down() {
    kubectl delete -f ./template/ingress-class.yaml
}


if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi

#Sample query: {namespace="example-tenant-5a2f",container="callee-service-application"}
