replicaCount: 1

image:
  repository: "bitnami/kafka"
  pullPolicy: IfNotPresent
  pullSecrets: 

podAnnotations:
  linkerd.io/inject: disabled
  sidecar.istio.io/inject: "false"

resourcesAnnotations:
  resources:
    requests:
      memory: 128M
      cpu: 250m

readinessProbe:
  initialDelaySeconds: 1

service:
  type: ClusterIP