apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  quarkus.security.users.embedded.users.service: {{ .Values.service.password | b64enc }}
  quarkus.security.users.embedded.roles.service: c3RhbmRhcmRfcm9sZQ==

