#!/bin/bash
source ../.values
COMMAND=$1
EMAIL=$2
PASSWORD=$3

[ -z "$EMAIL" ] && echo variable not set && exit
[ -z "$PASSWORD" ] && echo variable not set && exit

function delete_secret() {
  kubectl -n $1 delete secret --ignore-not-found docker-registry "$2"-secret
}

function create_secret() {
  delete_secret $1 $2
  kubectl -n $1 create secret docker-registry "$2"-secret \
    --docker-server=$2 \
    --docker-username=$EMAIL \
    --docker-password=$PASSWORD \
    --docker-email=$EMAIL
}

if [ "${COMMAND}" = "create" ]
then
    for namespace in ${namespaces_own[@]}; do
        for registry in ${registries[@]}; do
            create_secret $namespace $registry
        done
    done
elif [ "${COMMAND}" = "delete" ]
then
    for namespace in ${namespaces_own[@]}; do
        for registry in ${registries[@]}; do
            delete_secret $namespace $registry
        done
    done
else
    echo Doing nothing !
fi