#!/bin/bash
source .values
COMMAND=$1
EMAIL=$2
PASSWORD=$3

[ -z "$EMAIL" ] && echo variable not set && exit
[ -z "$PASSWORD" ] && echo variable not set && exit

function delete_secret() {
    kubectl --namespace default delete secret --ignore-not-found docker-registry "$1"-secret
}

function create_secret() {
    delete_secret $1
    kubectl --namespace default create secret docker-registry "$1"-secret \
      --docker-server=$1 \
      --docker-username=$EMAIL \
      --docker-password=$PASSWORD \
      --docker-email=$EMAIL
    kubectl annotate secret "$1"-secret kubed.appscode.com/sync="" --namespace default
}

if [ "${COMMAND}" = "create" ]
then
    for registry in ${registries[@]}; do
        create_secret $registry
    done
elif [ "${COMMAND}" = "delete" ]
then
    for registry in ${registries[@]}; do
        delete_secret $registry
    done
else
    echo Doing nothing !
fi