#!/bin/bash
COMMAND=$1

function input_secret() {
  [ -z "$registries" ] && exit
  
  echo We now need the credentials to login to artifactory docker registry
  read -p "email: " EMAIL < /dev/tty
  printf "password: "
  while IFS= read -p "$prompt" -r -s -n 1 char < /dev/tty; do
    if [[ $char == $'\0' ]]; then
      break
    fi
    prompt='*'
    PASSWORD+="$char"
  done
  echo "" # add echo to prevent -n errors
}

if [ "${COMMAND}" = "init" ]
then
    input_secret
    ./secret-manager create $EMAIL $PASSWORD
elif [ "${COMMAND}" = "prune" ]
then
    ./secret-manager delete "none" "none"
else
    echo Doing nothing !
fi






