replicaCount: 1
maxReplicas: 3

ingress:
  paths: /

image:
  repository: "goafabric/backstage" # image name
  pullPolicy: IfNotPresent #Always
  pullSecrets: 

resourcesAnnotations:
  resources:
    requests:
      memory: 128M
      cpu: 250m


readinessProbe:
  initialDelaySeconds: 2


service:
  type: ClusterIP
  port: 7007

oidc:
  enabled:




