apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ca
  namespace: cert-manager
spec:
  isCA: true

  commonName: {{ .Values.ingress.hosts}}
  dnsNames:
    - {{ .Values.ingress.hosts}}
  subject:
    organizations:
      - Example Organization

  secretName: root-certificate
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: my-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
