apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ include "application.fullname" . }}
spec:
  http:
    - name: {{ include "application.fullname" . }}
      match:
        hosts:
          - {{ .Values.ingress.hosts }}
        paths:
          - {{ .Values.ingress.paths }}
          - {{ .Values.ingress.paths }}/*
      backends:
        - serviceName: {{ include "application.fullname" . }}
          servicePort: http
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: false