#!/bin/bash
COMMAND=$1
PROFILE=$2

function up() {
    istioctl install -f ./templates/tracing.yml
}

function down() {
    #nothing here
    echo nothing done
}


if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi