apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  ARGOCD_AUTH_TOKEN: {{ .Values.argocd.auth.token | b64enc }}
