#!/bin/bash
source .values
COMMAND=$1
WORKSPACE=$TF_VAR_hostname

function apply() {
  (cd $1; terraform workspace select -or-create $WORKSPACE && terraform apply -auto-approve)
}

function destroy() {
  (cd $1; terraform workspace select -or-create $WORKSPACE && terraform destroy -auto-approve)
}

function up() {
    time(
    apply ../../infra/ingress_certs
    apply ../../mesh/linkerd
    apply ../../infra/dev/monitoring
    apply ../../infra/dev/loki
    #apply ../../infra/dev/oidc
    apply ../../core
    (cd ../../../helm/templates/infra/message-broker/; ./stack init)
    )
}

function down() {
    time(
    (cd ../../../helm/templates/infra/message-broker/; ./stack prune)
    destroy ../../core
    destroy ../../infra/dev/oidc
    destroy ../../infra/dev/monitoring
    apply ../../infra/dev/loki
    destroy ../../infra/ingress_certs
    destroy ../../mesh/linkerd
    )
}

if   [ "${COMMAND}" = "init" ]; then up;
elif [ "${COMMAND}" = "prune" ]; then down;

else echo Doing nothing !; fi