apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  spring.datasource.username: Y29yZQ==
  spring.datasource.password: {{ .Values.database.password | default "postgres" | b64enc }}