#!/bin/bash
COMMAND=$1
IMAGE_ARCH=$2


function configure() {
  kubectl exec -it vault-0 -n vault -- vault auth enable kubernetes

  kubectl exec -it vault-0 -n vault -- /bin/sh -c '
  vault write auth/kubernetes/config \
    token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
    kubernetes_host="https://${KUBERNETES_PORT_443_TCP_ADDR}:443" \
    kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  '
}

function up() {
  helm repo add hashicorp https://helm.releases.hashicorp.com
  helm install vault hashicorp/vault --wait --set "server.dev.enabled=true" --namespace vault --create-namespace --version 0.28.1

  configure
}

function down() {
  helm uninstall vault --namespace vault
}



if   [ "${COMMAND}" = "up" ]; then up;
elif [ "${COMMAND}" = "down" ]; then down;
elif [ "${COMMAND}" = "restart" ]; then down && up;
elif [ "${COMMAND}" = "lint" ]; then helm lint ./;
elif [ "${COMMAND}" = "proxy" ]; then proxy;

else echo Doing nothing !; fi