apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "application.fullname" . }}-pvc
  labels:
    {{- include "application.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{ if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
